// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/comm.proto

package pbdb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

type Hero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`             // 英雄id
	Lv       int32 `protobuf:"varint,3,opt,name=lv,proto3" json:"lv,omitempty"`             // 等级
	Star     int32 `protobuf:"varint,4,opt,name=star,proto3" json:"star,omitempty"`         // 星级
	CreateAt int64 `protobuf:"varint,5,opt,name=createAt,proto3" json:"createAt,omitempty"` //毫秒
	Stage    int32 `protobuf:"varint,6,opt,name=stage,proto3" json:"stage,omitempty"`       //阶段
}

func (x *Hero) Reset() {
	*x = Hero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hero) ProtoMessage() {}

func (x *Hero) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hero.ProtoReflect.Descriptor instead.
func (*Hero) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{0}
}

func (x *Hero) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hero) GetLv() int32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

func (x *Hero) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *Hero) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Hero) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

type Equip struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                        // 配置表ID
	Lv         int32   `protobuf:"varint,2,opt,name=lv,proto3" json:"lv,omitempty"`                        //强化等级
	ExtAttrIds []int32 `protobuf:"varint,3,rep,packed,name=extAttrIds,proto3" json:"extAttrIds,omitempty"` //附加属性
}

func (x *Equip) Reset() {
	*x = Equip{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Equip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Equip) ProtoMessage() {}

func (x *Equip) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Equip.ProtoReflect.Descriptor instead.
func (*Equip) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{1}
}

func (x *Equip) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Equip) GetLv() int32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

func (x *Equip) GetExtAttrIds() []int32 {
	if x != nil {
		return x.ExtAttrIds
	}
	return nil
}

//天赋
type Talent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points int32 `protobuf:"varint,1,opt,name=points,proto3" json:"points,omitempty"` //点数
	Lv     int32 `protobuf:"varint,2,opt,name=lv,proto3" json:"lv,omitempty"`         //天赋等级=技能等级
}

func (x *Talent) Reset() {
	*x = Talent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Talent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Talent) ProtoMessage() {}

func (x *Talent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Talent.ProtoReflect.Descriptor instead.
func (*Talent) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{2}
}

func (x *Talent) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *Talent) GetLv() int32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

//蓝量
type Mp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num           int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	LastRefreshAt int64 `protobuf:"varint,2,opt,name=lastRefreshAt,proto3" json:"lastRefreshAt,omitempty"` //最近刷新时间
}

func (x *Mp) Reset() {
	*x = Mp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mp) ProtoMessage() {}

func (x *Mp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mp.ProtoReflect.Descriptor instead.
func (*Mp) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{3}
}

func (x *Mp) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Mp) GetLastRefreshAt() int64 {
	if x != nil {
		return x.LastRefreshAt
	}
	return 0
}

//领主府
type LordsMansion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lv int32 `protobuf:"varint,1,opt,name=lv,proto3" json:"lv,omitempty"` //领主府等级
}

func (x *LordsMansion) Reset() {
	*x = LordsMansion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LordsMansion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LordsMansion) ProtoMessage() {}

func (x *LordsMansion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LordsMansion.ProtoReflect.Descriptor instead.
func (*LordsMansion) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{4}
}

func (x *LordsMansion) GetLv() int32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

//资源建筑建筑
type BuildingRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerNum int32 `protobuf:"varint,1,opt,name=workerNum,proto3" json:"workerNum,omitempty"` //工人数量
	Lv        int32 `protobuf:"varint,4,opt,name=lv,proto3" json:"lv,omitempty"`               //等级
}

func (x *BuildingRes) Reset() {
	*x = BuildingRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingRes) ProtoMessage() {}

func (x *BuildingRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingRes.ProtoReflect.Descriptor instead.
func (*BuildingRes) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{5}
}

func (x *BuildingRes) GetWorkerNum() int32 {
	if x != nil {
		return x.WorkerNum
	}
	return 0
}

func (x *BuildingRes) GetLv() int32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

//召唤界面信息
type ArtifactSummoningSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CostItemId int32 `protobuf:"varint,1,opt,name=costItemId,proto3" json:"costItemId,omitempty"` //需要消耗的道具id
	ArtifactId int32 `protobuf:"varint,2,opt,name=artifactId,proto3" json:"artifactId,omitempty"` //神器id
	IsBuy      bool  `protobuf:"varint,3,opt,name=isBuy,proto3" json:"isBuy,omitempty"`           //标记本来刷新是否购买
}

func (x *ArtifactSummoningSlot) Reset() {
	*x = ArtifactSummoningSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactSummoningSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactSummoningSlot) ProtoMessage() {}

func (x *ArtifactSummoningSlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactSummoningSlot.ProtoReflect.Descriptor instead.
func (*ArtifactSummoningSlot) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{6}
}

func (x *ArtifactSummoningSlot) GetCostItemId() int32 {
	if x != nil {
		return x.CostItemId
	}
	return 0
}

func (x *ArtifactSummoningSlot) GetArtifactId() int32 {
	if x != nil {
		return x.ArtifactId
	}
	return 0
}

func (x *ArtifactSummoningSlot) GetIsBuy() bool {
	if x != nil {
		return x.IsBuy
	}
	return false
}

//拥有的神器
type Artifact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lv       int32 `protobuf:"varint,1,opt,name=lv,proto3" json:"lv,omitempty"`             //等级
	Nums     int32 `protobuf:"varint,2,opt,name=nums,proto3" json:"nums,omitempty"`         //本体碎片数量
	CreateAt int64 `protobuf:"varint,3,opt,name=createAt,proto3" json:"createAt,omitempty"` //获取时间
	Id       int32 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`             //神器id
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{7}
}

func (x *Artifact) GetLv() int32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

func (x *Artifact) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *Artifact) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Artifact) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SkillMgr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderSkill   map[int32]*LeaderSkill    `protobuf:"bytes,1,rep,name=LeaderSkill,proto3" json:"LeaderSkill,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`    //主角技能使用 k-技能id
	HeroSkill     map[string]*HeroSkill     `protobuf:"bytes,2,rep,name=HeroSkill,proto3" json:"HeroSkill,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`         //英雄技能使用 k-skillKey
	ArtifactSkill map[string]*ArtifactSkill `protobuf:"bytes,3,rep,name=ArtifactSkill,proto3" json:"ArtifactSkill,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //神器技能使用 k-skillKey
	HeroSkillSort []*HeroSkillSort          `protobuf:"bytes,4,rep,name=heroSkillSort,proto3" json:"heroSkillSort,omitempty"`                                                                                         //英雄技能先后顺序
}

func (x *SkillMgr) Reset() {
	*x = SkillMgr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkillMgr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillMgr) ProtoMessage() {}

func (x *SkillMgr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillMgr.ProtoReflect.Descriptor instead.
func (*SkillMgr) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{8}
}

func (x *SkillMgr) GetLeaderSkill() map[int32]*LeaderSkill {
	if x != nil {
		return x.LeaderSkill
	}
	return nil
}

func (x *SkillMgr) GetHeroSkill() map[string]*HeroSkill {
	if x != nil {
		return x.HeroSkill
	}
	return nil
}

func (x *SkillMgr) GetArtifactSkill() map[string]*ArtifactSkill {
	if x != nil {
		return x.ArtifactSkill
	}
	return nil
}

func (x *SkillMgr) GetHeroSkillSort() []*HeroSkillSort {
	if x != nil {
		return x.HeroSkillSort
	}
	return nil
}

type HeroSkillSort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillId int32 `protobuf:"varint,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	HeroId  int32 `protobuf:"varint,2,opt,name=heroId,proto3" json:"heroId,omitempty"`
}

func (x *HeroSkillSort) Reset() {
	*x = HeroSkillSort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroSkillSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroSkillSort) ProtoMessage() {}

func (x *HeroSkillSort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroSkillSort.ProtoReflect.Descriptor instead.
func (*HeroSkillSort) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{9}
}

func (x *HeroSkillSort) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *HeroSkillSort) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

type LeaderSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UseAt   int64 `protobuf:"varint,1,opt,name=useAt,proto3" json:"useAt,omitempty"`
	SkillId int32 `protobuf:"varint,2,opt,name=skillId,proto3" json:"skillId,omitempty"`
}

func (x *LeaderSkill) Reset() {
	*x = LeaderSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderSkill) ProtoMessage() {}

func (x *LeaderSkill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderSkill.ProtoReflect.Descriptor instead.
func (*LeaderSkill) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{10}
}

func (x *LeaderSkill) GetUseAt() int64 {
	if x != nil {
		return x.UseAt
	}
	return 0
}

func (x *LeaderSkill) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

type HeroSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UseAt   int64 `protobuf:"varint,1,opt,name=useAt,proto3" json:"useAt,omitempty"`
	HeroId  int32 `protobuf:"varint,2,opt,name=heroId,proto3" json:"heroId,omitempty"` //英雄id
	Ext     int32 `protobuf:"varint,3,opt,name=ext,proto3" json:"ext,omitempty"`       //额外待定¬
	SkillId int32 `protobuf:"varint,4,opt,name=skillId,proto3" json:"skillId,omitempty"`
}

func (x *HeroSkill) Reset() {
	*x = HeroSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroSkill) ProtoMessage() {}

func (x *HeroSkill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroSkill.ProtoReflect.Descriptor instead.
func (*HeroSkill) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{11}
}

func (x *HeroSkill) GetUseAt() int64 {
	if x != nil {
		return x.UseAt
	}
	return 0
}

func (x *HeroSkill) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroSkill) GetExt() int32 {
	if x != nil {
		return x.Ext
	}
	return 0
}

func (x *HeroSkill) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

type ArtifactSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UseAt      int64 `protobuf:"varint,1,opt,name=useAt,proto3" json:"useAt,omitempty"`
	ArtifactId int32 `protobuf:"varint,2,opt,name=artifactId,proto3" json:"artifactId,omitempty"` //神器id
	SkillId    int32 `protobuf:"varint,3,opt,name=skillId,proto3" json:"skillId,omitempty"`
}

func (x *ArtifactSkill) Reset() {
	*x = ArtifactSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactSkill) ProtoMessage() {}

func (x *ArtifactSkill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactSkill.ProtoReflect.Descriptor instead.
func (*ArtifactSkill) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{12}
}

func (x *ArtifactSkill) GetUseAt() int64 {
	if x != nil {
		return x.UseAt
	}
	return 0
}

func (x *ArtifactSkill) GetArtifactId() int32 {
	if x != nil {
		return x.ArtifactId
	}
	return 0
}

func (x *ArtifactSkill) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

//佣兵
type Mercenary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId         int32   `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`                 //复制的任务id
	StartTaskAt    int64   `protobuf:"varint,2,opt,name=startTaskAt,proto3" json:"startTaskAt,omitempty"`       //任务开始执行时间，0 没有执行任务 -1 任务已经领取 >0 任务开始执行的时间戳
	LastRefreshDay int64   `protobuf:"varint,3,opt,name=lastRefreshDay,proto3" json:"lastRefreshDay,omitempty"` //最近刷新天
	MercenaryId    int32   `protobuf:"varint,4,opt,name=mercenaryId,proto3" json:"mercenaryId,omitempty"`       //佣兵id
	Name           int32   `protobuf:"varint,5,opt,name=name,proto3" json:"name,omitempty"`                     //佣兵名字
	TaskList       []int32 `protobuf:"varint,6,rep,packed,name=taskList,proto3" json:"taskList,omitempty"`      //任务列表
}

func (x *Mercenary) Reset() {
	*x = Mercenary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mercenary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mercenary) ProtoMessage() {}

func (x *Mercenary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mercenary.ProtoReflect.Descriptor instead.
func (*Mercenary) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{13}
}

func (x *Mercenary) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *Mercenary) GetStartTaskAt() int64 {
	if x != nil {
		return x.StartTaskAt
	}
	return 0
}

func (x *Mercenary) GetLastRefreshDay() int64 {
	if x != nil {
		return x.LastRefreshDay
	}
	return 0
}

func (x *Mercenary) GetMercenaryId() int32 {
	if x != nil {
		return x.MercenaryId
	}
	return 0
}

func (x *Mercenary) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *Mercenary) GetTaskList() []int32 {
	if x != nil {
		return x.TaskList
	}
	return nil
}

//爬塔玩法
type InsClimbTower struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxLevel int32   `protobuf:"varint,1,opt,name=maxLevel,proto3" json:"maxLevel,omitempty"`        //目前通过的最大关卡
	SkillIds []int32 `protobuf:"varint,2,rep,packed,name=skillIds,proto3" json:"skillIds,omitempty"` //装备的技能id
}

func (x *InsClimbTower) Reset() {
	*x = InsClimbTower{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsClimbTower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsClimbTower) ProtoMessage() {}

func (x *InsClimbTower) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsClimbTower.ProtoReflect.Descriptor instead.
func (*InsClimbTower) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{14}
}

func (x *InsClimbTower) GetMaxLevel() int32 {
	if x != nil {
		return x.MaxLevel
	}
	return 0
}

func (x *InsClimbTower) GetSkillIds() []int32 {
	if x != nil {
		return x.SkillIds
	}
	return nil
}

//Boss玩法
type InsBoss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshAt int64 `protobuf:"varint,1,opt,name=refreshAt,proto3" json:"refreshAt,omitempty"` //最近刷新时间
	DamageMax int64 `protobuf:"varint,2,opt,name=damageMax,proto3" json:"damageMax,omitempty"` //今日最高伤害
}

func (x *InsBoss) Reset() {
	*x = InsBoss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsBoss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsBoss) ProtoMessage() {}

func (x *InsBoss) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsBoss.ProtoReflect.Descriptor instead.
func (*InsBoss) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{15}
}

func (x *InsBoss) GetRefreshAt() int64 {
	if x != nil {
		return x.RefreshAt
	}
	return 0
}

func (x *InsBoss) GetDamageMax() int64 {
	if x != nil {
		return x.DamageMax
	}
	return 0
}

//勇士令
type WarriorOrderMgr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsBuy    int64           `protobuf:"varint,1,opt,name=isBuy,proto3" json:"isBuy,omitempty"`                                                                                                //购买豪华版特权时间 勇士令 0-没有购买
	BaseGift map[int32]int64 `protobuf:"bytes,2,rep,name=baseGift,proto3" json:"baseGift,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //已经领取的基础板 k-礼包id v-时间戳
	VipGift  map[int32]int64 `protobuf:"bytes,3,rep,name=vipGift,proto3" json:"vipGift,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`   //已经领取的豪华版 k-礼包id v-时间戳
}

func (x *WarriorOrderMgr) Reset() {
	*x = WarriorOrderMgr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WarriorOrderMgr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarriorOrderMgr) ProtoMessage() {}

func (x *WarriorOrderMgr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarriorOrderMgr.ProtoReflect.Descriptor instead.
func (*WarriorOrderMgr) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{16}
}

func (x *WarriorOrderMgr) GetIsBuy() int64 {
	if x != nil {
		return x.IsBuy
	}
	return 0
}

func (x *WarriorOrderMgr) GetBaseGift() map[int32]int64 {
	if x != nil {
		return x.BaseGift
	}
	return nil
}

func (x *WarriorOrderMgr) GetVipGift() map[int32]int64 {
	if x != nil {
		return x.VipGift
	}
	return nil
}

//首充
type InitialChargeMgr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChargeAt  int64   `protobuf:"varint,2,opt,name=chargeAt,proto3" json:"chargeAt,omitempty"`          //充值时间 0-未首充
	DrawGifts []int32 `protobuf:"varint,3,rep,packed,name=drawGifts,proto3" json:"drawGifts,omitempty"` //领取的giftId
}

func (x *InitialChargeMgr) Reset() {
	*x = InitialChargeMgr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitialChargeMgr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialChargeMgr) ProtoMessage() {}

func (x *InitialChargeMgr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialChargeMgr.ProtoReflect.Descriptor instead.
func (*InitialChargeMgr) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{17}
}

func (x *InitialChargeMgr) GetChargeAt() int64 {
	if x != nil {
		return x.ChargeAt
	}
	return 0
}

func (x *InitialChargeMgr) GetDrawGifts() []int32 {
	if x != nil {
		return x.DrawGifts
	}
	return nil
}

//MonthCard 月卡
type MonthCardMgr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NormalCard  *Card `protobuf:"bytes,1,opt,name=normalCard,proto3" json:"normalCard,omitempty"`   //普通月卡
	ForeverCard *Card `protobuf:"bytes,2,opt,name=foreverCard,proto3" json:"foreverCard,omitempty"` //终身月卡
}

func (x *MonthCardMgr) Reset() {
	*x = MonthCardMgr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonthCardMgr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthCardMgr) ProtoMessage() {}

func (x *MonthCardMgr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthCardMgr.ProtoReflect.Descriptor instead.
func (*MonthCardMgr) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{18}
}

func (x *MonthCardMgr) GetNormalCard() *Card {
	if x != nil {
		return x.NormalCard
	}
	return nil
}

func (x *MonthCardMgr) GetForeverCard() *Card {
	if x != nil {
		return x.ForeverCard
	}
	return nil
}

//月卡
type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DrawDayAt int64 `protobuf:"varint,1,opt,name=drawDayAt,proto3" json:"drawDayAt,omitempty"` //最近领取的时间0点
	BuyAt     int64 `protobuf:"varint,2,opt,name=buyAt,proto3" json:"buyAt,omitempty"`         //购买时间
	AllNums   int64 `protobuf:"varint,3,opt,name=allNums,proto3" json:"allNums,omitempty"`     //累计获得
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{19}
}

func (x *Card) GetDrawDayAt() int64 {
	if x != nil {
		return x.DrawDayAt
	}
	return 0
}

func (x *Card) GetBuyAt() int64 {
	if x != nil {
		return x.BuyAt
	}
	return 0
}

func (x *Card) GetAllNums() int64 {
	if x != nil {
		return x.AllNums
	}
	return 0
}

//召唤
type GachaMgr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FreeAt int64 `protobuf:"varint,1,opt,name=freeAt,proto3" json:"freeAt,omitempty"` //上次免费高级召唤使用时间(毫秒）
	Points int32 `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"` // 召唤积分
	Floors int32 `protobuf:"varint,3,opt,name=floors,proto3" json:"floors,omitempty"` //保底次数
}

func (x *GachaMgr) Reset() {
	*x = GachaMgr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GachaMgr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GachaMgr) ProtoMessage() {}

func (x *GachaMgr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GachaMgr.ProtoReflect.Descriptor instead.
func (*GachaMgr) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{20}
}

func (x *GachaMgr) GetFreeAt() int64 {
	if x != nil {
		return x.FreeAt
	}
	return 0
}

func (x *GachaMgr) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *GachaMgr) GetFloors() int32 {
	if x != nil {
		return x.Floors
	}
	return 0
}

//商店
type ShopMgr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshAt  int64       `protobuf:"varint,1,opt,name=refreshAt,proto3" json:"refreshAt,omitempty"`  //UTC-O点刷新限购次数和物品
	AdvShop    *AdvShop    `protobuf:"bytes,2,opt,name=AdvShop,proto3" json:"AdvShop,omitempty"`       //广告商店
	NormalShop *NormalShop `protobuf:"bytes,3,opt,name=NormalShop,proto3" json:"NormalShop,omitempty"` //常规商店
}

func (x *ShopMgr) Reset() {
	*x = ShopMgr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopMgr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopMgr) ProtoMessage() {}

func (x *ShopMgr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopMgr.ProtoReflect.Descriptor instead.
func (*ShopMgr) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{21}
}

func (x *ShopMgr) GetRefreshAt() int64 {
	if x != nil {
		return x.RefreshAt
	}
	return 0
}

func (x *ShopMgr) GetAdvShop() *AdvShop {
	if x != nil {
		return x.AdvShop
	}
	return nil
}

func (x *ShopMgr) GetNormalShop() *NormalShop {
	if x != nil {
		return x.NormalShop
	}
	return nil
}

type AdvShop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DrawGoodIds map[int32]int32 `protobuf:"bytes,1,rep,name=drawGoodIds,proto3" json:"drawGoodIds,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //已经领取的商品 k-id v-领取次数
}

func (x *AdvShop) Reset() {
	*x = AdvShop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdvShop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvShop) ProtoMessage() {}

func (x *AdvShop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvShop.ProtoReflect.Descriptor instead.
func (*AdvShop) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{22}
}

func (x *AdvShop) GetDrawGoodIds() map[int32]int32 {
	if x != nil {
		return x.DrawGoodIds
	}
	return nil
}

type NormalShop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DrawGoodIds map[int32]int32 `protobuf:"bytes,1,rep,name=drawGoodIds,proto3" json:"drawGoodIds,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //已经领取的商品 k-id v-购买次数
}

func (x *NormalShop) Reset() {
	*x = NormalShop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NormalShop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalShop) ProtoMessage() {}

func (x *NormalShop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalShop.ProtoReflect.Descriptor instead.
func (*NormalShop) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{23}
}

func (x *NormalShop) GetDrawGoodIds() map[int32]int32 {
	if x != nil {
		return x.DrawGoodIds
	}
	return nil
}

//钻石商店
type DiamondShopMgr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DrawGoodIds map[int32]int64 `protobuf:"bytes,1,rep,name=drawGoodIds,proto3" json:"drawGoodIds,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //已经充值的档位 k-id v-最近购买时间
}

func (x *DiamondShopMgr) Reset() {
	*x = DiamondShopMgr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiamondShopMgr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiamondShopMgr) ProtoMessage() {}

func (x *DiamondShopMgr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiamondShopMgr.ProtoReflect.Descriptor instead.
func (*DiamondShopMgr) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{24}
}

func (x *DiamondShopMgr) GetDrawGoodIds() map[int32]int64 {
	if x != nil {
		return x.DrawGoodIds
	}
	return nil
}

type DailyTaskPer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nums   int32 `protobuf:"varint,1,opt,name=nums,proto3" json:"nums,omitempty"`     //任务达成数量
	IsDraw bool  `protobuf:"varint,2,opt,name=isDraw,proto3" json:"isDraw,omitempty"` //是否领取
}

func (x *DailyTaskPer) Reset() {
	*x = DailyTaskPer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyTaskPer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyTaskPer) ProtoMessage() {}

func (x *DailyTaskPer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyTaskPer.ProtoReflect.Descriptor instead.
func (*DailyTaskPer) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{25}
}

func (x *DailyTaskPer) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

func (x *DailyTaskPer) GetIsDraw() bool {
	if x != nil {
		return x.IsDraw
	}
	return false
}

type Setting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangedName bool `protobuf:"varint,4,opt,name=changedName,proto3" json:"changedName,omitempty"` //是否改过名字 true-是 false-不是
}

func (x *Setting) Reset() {
	*x = Setting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting) ProtoMessage() {}

func (x *Setting) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting.ProtoReflect.Descriptor instead.
func (*Setting) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{26}
}

func (x *Setting) GetChangedName() bool {
	if x != nil {
		return x.ChangedName
	}
	return false
}

type ExtStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastLoginZeroAt int64 `protobuf:"varint,1,opt,name=lastLoginZeroAt,proto3" json:"lastLoginZeroAt,omitempty"` //最近一次登陆时间
}

func (x *ExtStatus) Reset() {
	*x = ExtStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comm_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtStatus) ProtoMessage() {}

func (x *ExtStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comm_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtStatus.ProtoReflect.Descriptor instead.
func (*ExtStatus) Descriptor() ([]byte, []int) {
	return file_proto_comm_proto_rawDescGZIP(), []int{27}
}

func (x *ExtStatus) GetLastLoginZeroAt() int64 {
	if x != nil {
		return x.LastLoginZeroAt
	}
	return 0
}

var File_proto_comm_proto protoreflect.FileDescriptor

var file_proto_comm_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x04, 0x48, 0x65, 0x72, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x76,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6c, 0x76, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74,
	0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x61, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x22, 0x47, 0x0a, 0x05, 0x45, 0x71, 0x75, 0x69, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x76, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6c, 0x76, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x74,
	0x41, 0x74, 0x74, 0x72, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x65,
	0x78, 0x74, 0x41, 0x74, 0x74, 0x72, 0x49, 0x64, 0x73, 0x22, 0x30, 0x0a, 0x06, 0x54, 0x61, 0x6c,
	0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6c,
	0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6c, 0x76, 0x22, 0x3c, 0x0a, 0x02, 0x4d,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74,
	0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x74, 0x22, 0x1e, 0x0a, 0x0c, 0x4c, 0x6f, 0x72,
	0x64, 0x73, 0x4d, 0x61, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x76, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6c, 0x76, 0x22, 0x3b, 0x0a, 0x0b, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x76, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x6c, 0x76, 0x22, 0x6d, 0x0a, 0x15, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x6c, 0x6f, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x73, 0x42, 0x75, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x69, 0x73, 0x42, 0x75, 0x79, 0x22, 0x5a, 0x0a, 0x08, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6c,
	0x76, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x6e, 0x75, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x22, 0xe4, 0x03, 0x0a, 0x08, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x4d, 0x67, 0x72, 0x12, 0x3c,
	0x0a, 0x0b, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x4d, 0x67, 0x72, 0x2e, 0x4c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0b, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x36, 0x0a, 0x09,
	0x48, 0x65, 0x72, 0x6f, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x4d, 0x67, 0x72, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x48, 0x65, 0x72, 0x6f, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x42, 0x0a, 0x0d, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x4d, 0x67, 0x72, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x41, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x34, 0x0a, 0x0d, 0x68, 0x65, 0x72, 0x6f,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x53, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x68, 0x65, 0x72, 0x6f, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x53, 0x6f, 0x72, 0x74, 0x52,
	0x0d, 0x68, 0x65, 0x72, 0x6f, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x53, 0x6f, 0x72, 0x74, 0x1a, 0x4c,
	0x0a, 0x10, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x48, 0x0a, 0x0e,
	0x48, 0x65, 0x72, 0x6f, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x20, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x50, 0x0a, 0x12, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x24,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x41, 0x0a, 0x0d, 0x68, 0x65, 0x72, 0x6f,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x0b, 0x4c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73,
	0x65, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x75, 0x73, 0x65, 0x41, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x65, 0x0a, 0x09, 0x48, 0x65,
	0x72, 0x6f, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x41, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x75, 0x73, 0x65, 0x41, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68,
	0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49,
	0x64, 0x22, 0x5f, 0x0a, 0x0d, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x75, 0x73, 0x65, 0x41, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x49, 0x64, 0x22, 0xbf, 0x01, 0x0a, 0x09, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x61,
	0x73, 0x74, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x44, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x44,
	0x61, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x79, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x73, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x43, 0x6c, 0x69, 0x6d, 0x62,
	0x54, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x08, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x45, 0x0a,
	0x07, 0x49, 0x6e, 0x73, 0x42, 0x6f, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x72,
	0x65, 0x73, 0x68, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65,
	0x4d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x61, 0x6d, 0x61, 0x67,
	0x65, 0x4d, 0x61, 0x78, 0x22, 0x95, 0x02, 0x0a, 0x0f, 0x57, 0x61, 0x72, 0x72, 0x69, 0x6f, 0x72,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x67, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x42, 0x75,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x73, 0x42, 0x75, 0x79, 0x12, 0x3a,
	0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x47, 0x69, 0x66, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x57, 0x61, 0x72, 0x72, 0x69, 0x6f, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d,
	0x67, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x47, 0x69, 0x66, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x47, 0x69, 0x66, 0x74, 0x12, 0x37, 0x0a, 0x07, 0x76, 0x69,
	0x70, 0x47, 0x69, 0x66, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x57, 0x61,
	0x72, 0x72, 0x69, 0x6f, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x67, 0x72, 0x2e, 0x56, 0x69,
	0x70, 0x47, 0x69, 0x66, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x76, 0x69, 0x70, 0x47,
	0x69, 0x66, 0x74, 0x1a, 0x3b, 0x0a, 0x0d, 0x42, 0x61, 0x73, 0x65, 0x47, 0x69, 0x66, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x1a, 0x3a, 0x0a, 0x0c, 0x56, 0x69, 0x70, 0x47, 0x69, 0x66, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x4c, 0x0a, 0x10,
	0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x4d, 0x67, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x64, 0x72, 0x61, 0x77, 0x47, 0x69, 0x66, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x09, 0x64, 0x72, 0x61, 0x77, 0x47, 0x69, 0x66, 0x74, 0x73, 0x22, 0x5e, 0x0a, 0x0c, 0x4d, 0x6f,
	0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x4d, 0x67, 0x72, 0x12, 0x25, 0x0a, 0x0a, 0x6e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x43, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x0a, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x27, 0x0a, 0x0b, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x0b, 0x66,
	0x6f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x22, 0x54, 0x0a, 0x04, 0x43, 0x61,
	0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x72, 0x61, 0x77, 0x44, 0x61, 0x79, 0x41, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x64, 0x72, 0x61, 0x77, 0x44, 0x61, 0x79, 0x41, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x75, 0x79, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x62, 0x75, 0x79, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x6c, 0x4e, 0x75, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x6c, 0x6c, 0x4e, 0x75, 0x6d, 0x73,
	0x22, 0x52, 0x0a, 0x08, 0x47, 0x61, 0x63, 0x68, 0x61, 0x4d, 0x67, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x72, 0x65, 0x65, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x72,
	0x65, 0x65, 0x41, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x6c,
	0x6f, 0x6f, 0x72, 0x73, 0x22, 0x78, 0x0a, 0x07, 0x53, 0x68, 0x6f, 0x70, 0x4d, 0x67, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x74, 0x12, 0x22, 0x0a,
	0x07, 0x41, 0x64, 0x76, 0x53, 0x68, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x41, 0x64, 0x76, 0x53, 0x68, 0x6f, 0x70, 0x52, 0x07, 0x41, 0x64, 0x76, 0x53, 0x68, 0x6f,
	0x70, 0x12, 0x2b, 0x0a, 0x0a, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x53, 0x68,
	0x6f, 0x70, 0x52, 0x0a, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x22, 0x86,
	0x01, 0x0a, 0x07, 0x41, 0x64, 0x76, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x3b, 0x0a, 0x0b, 0x64, 0x72,
	0x61, 0x77, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x41, 0x64, 0x76, 0x53, 0x68, 0x6f, 0x70, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x47, 0x6f,
	0x6f, 0x64, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x64, 0x72, 0x61, 0x77,
	0x47, 0x6f, 0x6f, 0x64, 0x49, 0x64, 0x73, 0x1a, 0x3e, 0x0a, 0x10, 0x44, 0x72, 0x61, 0x77, 0x47,
	0x6f, 0x6f, 0x64, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x8c, 0x01, 0x0a, 0x0a, 0x4e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x12, 0x3e, 0x0a, 0x0b, 0x64, 0x72, 0x61, 0x77, 0x47, 0x6f,
	0x6f, 0x64, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x4e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x53, 0x68, 0x6f, 0x70, 0x2e, 0x44, 0x72, 0x61, 0x77, 0x47, 0x6f, 0x6f,
	0x64, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x64, 0x72, 0x61, 0x77, 0x47,
	0x6f, 0x6f, 0x64, 0x49, 0x64, 0x73, 0x1a, 0x3e, 0x0a, 0x10, 0x44, 0x72, 0x61, 0x77, 0x47, 0x6f,
	0x6f, 0x64, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x94, 0x01, 0x0a, 0x0e, 0x44, 0x69, 0x61, 0x6d, 0x6f,
	0x6e, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x4d, 0x67, 0x72, 0x12, 0x42, 0x0a, 0x0b, 0x64, 0x72, 0x61,
	0x77, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x44, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x53, 0x68, 0x6f, 0x70, 0x4d, 0x67, 0x72, 0x2e,
	0x44, 0x72, 0x61, 0x77, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x0b, 0x64, 0x72, 0x61, 0x77, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x64, 0x73, 0x1a, 0x3e, 0x0a,
	0x10, 0x44, 0x72, 0x61, 0x77, 0x47, 0x6f, 0x6f, 0x64, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3a, 0x0a,
	0x0c, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x54, 0x61, 0x73, 0x6b, 0x50, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x75, 0x6d,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x44, 0x72, 0x61, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x69, 0x73, 0x44, 0x72, 0x61, 0x77, 0x22, 0x2b, 0x0a, 0x07, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x35, 0x0a, 0x09, 0x45, 0x78, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x5a, 0x65, 0x72, 0x6f, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x6c, 0x61,
	0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x5a, 0x65, 0x72, 0x6f, 0x41, 0x74, 0x42, 0x0d, 0x5a,
	0x0b, 0x2e, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x64, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_comm_proto_rawDescOnce sync.Once
	file_proto_comm_proto_rawDescData = file_proto_comm_proto_rawDesc
)

func file_proto_comm_proto_rawDescGZIP() []byte {
	file_proto_comm_proto_rawDescOnce.Do(func() {
		file_proto_comm_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_comm_proto_rawDescData)
	})
	return file_proto_comm_proto_rawDescData
}

var file_proto_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_comm_proto_goTypes = []interface{}{
	(*Hero)(nil),                  // 0: Hero
	(*Equip)(nil),                 // 1: Equip
	(*Talent)(nil),                // 2: Talent
	(*Mp)(nil),                    // 3: Mp
	(*LordsMansion)(nil),          // 4: LordsMansion
	(*BuildingRes)(nil),           // 5: BuildingRes
	(*ArtifactSummoningSlot)(nil), // 6: ArtifactSummoningSlot
	(*Artifact)(nil),              // 7: Artifact
	(*SkillMgr)(nil),              // 8: SkillMgr
	(*HeroSkillSort)(nil),         // 9: heroSkillSort
	(*LeaderSkill)(nil),           // 10: LeaderSkill
	(*HeroSkill)(nil),             // 11: HeroSkill
	(*ArtifactSkill)(nil),         // 12: ArtifactSkill
	(*Mercenary)(nil),             // 13: Mercenary
	(*InsClimbTower)(nil),         // 14: InsClimbTower
	(*InsBoss)(nil),               // 15: InsBoss
	(*WarriorOrderMgr)(nil),       // 16: WarriorOrderMgr
	(*InitialChargeMgr)(nil),      // 17: InitialChargeMgr
	(*MonthCardMgr)(nil),          // 18: MonthCardMgr
	(*Card)(nil),                  // 19: Card
	(*GachaMgr)(nil),              // 20: GachaMgr
	(*ShopMgr)(nil),               // 21: ShopMgr
	(*AdvShop)(nil),               // 22: AdvShop
	(*NormalShop)(nil),            // 23: NormalShop
	(*DiamondShopMgr)(nil),        // 24: DiamondShopMgr
	(*DailyTaskPer)(nil),          // 25: DailyTaskPer
	(*Setting)(nil),               // 26: Setting
	(*ExtStatus)(nil),             // 27: ExtStatus
	nil,                           // 28: SkillMgr.LeaderSkillEntry
	nil,                           // 29: SkillMgr.HeroSkillEntry
	nil,                           // 30: SkillMgr.ArtifactSkillEntry
	nil,                           // 31: WarriorOrderMgr.BaseGiftEntry
	nil,                           // 32: WarriorOrderMgr.VipGiftEntry
	nil,                           // 33: AdvShop.DrawGoodIdsEntry
	nil,                           // 34: NormalShop.DrawGoodIdsEntry
	nil,                           // 35: DiamondShopMgr.DrawGoodIdsEntry
}
var file_proto_comm_proto_depIdxs = []int32{
	28, // 0: SkillMgr.LeaderSkill:type_name -> SkillMgr.LeaderSkillEntry
	29, // 1: SkillMgr.HeroSkill:type_name -> SkillMgr.HeroSkillEntry
	30, // 2: SkillMgr.ArtifactSkill:type_name -> SkillMgr.ArtifactSkillEntry
	9,  // 3: SkillMgr.heroSkillSort:type_name -> heroSkillSort
	31, // 4: WarriorOrderMgr.baseGift:type_name -> WarriorOrderMgr.BaseGiftEntry
	32, // 5: WarriorOrderMgr.vipGift:type_name -> WarriorOrderMgr.VipGiftEntry
	19, // 6: MonthCardMgr.normalCard:type_name -> Card
	19, // 7: MonthCardMgr.foreverCard:type_name -> Card
	22, // 8: ShopMgr.AdvShop:type_name -> AdvShop
	23, // 9: ShopMgr.NormalShop:type_name -> NormalShop
	33, // 10: AdvShop.drawGoodIds:type_name -> AdvShop.DrawGoodIdsEntry
	34, // 11: NormalShop.drawGoodIds:type_name -> NormalShop.DrawGoodIdsEntry
	35, // 12: DiamondShopMgr.drawGoodIds:type_name -> DiamondShopMgr.DrawGoodIdsEntry
	10, // 13: SkillMgr.LeaderSkillEntry.value:type_name -> LeaderSkill
	11, // 14: SkillMgr.HeroSkillEntry.value:type_name -> HeroSkill
	12, // 15: SkillMgr.ArtifactSkillEntry.value:type_name -> ArtifactSkill
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_comm_proto_init() }
func file_proto_comm_proto_init() {
	if File_proto_comm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_comm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Equip); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Talent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LordsMansion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildingRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactSummoningSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Artifact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkillMgr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroSkillSort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mercenary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsClimbTower); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsBoss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WarriorOrderMgr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitialChargeMgr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonthCardMgr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GachaMgr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopMgr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdvShop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NormalShop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiamondShopMgr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyTaskPer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Setting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comm_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_comm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_comm_proto_goTypes,
		DependencyIndexes: file_proto_comm_proto_depIdxs,
		MessageInfos:      file_proto_comm_proto_msgTypes,
	}.Build()
	File_proto_comm_proto = out.File
	file_proto_comm_proto_rawDesc = nil
	file_proto_comm_proto_goTypes = nil
	file_proto_comm_proto_depIdxs = nil
}
