// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic.proto

package pbreq

import (
	context "context"
	pbgo "git.dhgames.cn/svr_comm/gclient/gate/pbgo"
	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	strconv "strconv"
	sync "sync"
)

//==================== Sync ====================//
//数据同步 grp:10, cmd:1
type ReqSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqSync) Reset() {
	*x = ReqSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqSync) ProtoMessage() {}

func (x *ReqSync) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqSync.ProtoReflect.Descriptor instead.
func (*ReqSync) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{0}
}

type RspSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	SvrTime int64      `protobuf:"varint,2,opt,name=svrTime,proto3" json:"svrTime,omitempty"` //服务器当前时间【时间戳 秒】
	RoleMgr *RoleMgr   `protobuf:"bytes,3,opt,name=roleMgr,proto3" json:"roleMgr,omitempty"`  // 角色信息
	Bag     *Bag       `protobuf:"bytes,5,opt,name=bag,proto3" json:"bag,omitempty"`          // 背包信息
	MailMgr []*MailMgr `protobuf:"bytes,15,rep,name=MailMgr,proto3" json:"MailMgr,omitempty"` // 邮件
}

func (x *RspSync) Reset() {
	*x = RspSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspSync) ProtoMessage() {}

func (x *RspSync) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspSync.ProtoReflect.Descriptor instead.
func (*RspSync) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{1}
}

func (x *RspSync) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RspSync) GetSvrTime() int64 {
	if x != nil {
		return x.SvrTime
	}
	return 0
}

func (x *RspSync) GetRoleMgr() *RoleMgr {
	if x != nil {
		return x.RoleMgr
	}
	return nil
}

func (x *RspSync) GetBag() *Bag {
	if x != nil {
		return x.Bag
	}
	return nil
}

func (x *RspSync) GetMailMgr() []*MailMgr {
	if x != nil {
		return x.MailMgr
	}
	return nil
}

//==================== GM ====================//
//GM命令 grp:11, cmd:1
type ReqGm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type GMType `protobuf:"varint,1,opt,name=type,proto3,enum=RE.Proto.GMType" json:"type,omitempty"` //命令类型
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                       // 数据
}

func (x *ReqGm) Reset() {
	*x = ReqGm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGm) ProtoMessage() {}

func (x *ReqGm) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGm.ProtoReflect.Descriptor instead.
func (*ReqGm) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{2}
}

func (x *ReqGm) GetType() GMType {
	if x != nil {
		return x.Type
	}
	return GMType_AddItem
}

func (x *ReqGm) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RspGm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 0成功
	Rewards *Rewards `protobuf:"bytes,2,opt,name=rewards,proto3" json:"rewards,omitempty"`
	Type    GMType   `protobuf:"varint,3,opt,name=type,proto3,enum=RE.Proto.GMType" json:"type,omitempty"` //命令类型
	ExtData string   `protobuf:"bytes,4,opt,name=ExtData,proto3" json:"ExtData,omitempty"`                 //额外数据
}

func (x *RspGm) Reset() {
	*x = RspGm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspGm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspGm) ProtoMessage() {}

func (x *RspGm) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspGm.ProtoReflect.Descriptor instead.
func (*RspGm) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{3}
}

func (x *RspGm) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RspGm) GetRewards() *Rewards {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *RspGm) GetType() GMType {
	if x != nil {
		return x.Type
	}
	return GMType_AddItem
}

func (x *RspGm) GetExtData() string {
	if x != nil {
		return x.ExtData
	}
	return ""
}

//==================== 装备、物品 ====================//
//使用道具 grp:12,cmd:1
type ReqUseItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int32 `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"` //道具id
	Num    int32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`       //数量
}

func (x *ReqUseItem) Reset() {
	*x = ReqUseItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUseItem) ProtoMessage() {}

func (x *ReqUseItem) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUseItem.ProtoReflect.Descriptor instead.
func (*ReqUseItem) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{4}
}

func (x *ReqUseItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ReqUseItem) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type RspUseItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`  // 0成功
	Rewards *Rewards `protobuf:"bytes,2,opt,name=rewards,proto3" json:"rewards,omitempty"` //奖励
	ItemId  int32    `protobuf:"varint,3,opt,name=itemId,proto3" json:"itemId,omitempty"`  //道具id
	Num     int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`        //数量
}

func (x *RspUseItem) Reset() {
	*x = RspUseItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspUseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspUseItem) ProtoMessage() {}

func (x *RspUseItem) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspUseItem.ProtoReflect.Descriptor instead.
func (*RspUseItem) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{5}
}

func (x *RspUseItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RspUseItem) GetRewards() *Rewards {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *RspUseItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *RspUseItem) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

//==================== 邮件 ====================//
// 阅读邮件 grp:13, cmd:1
type ReqMailRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailId int32 `protobuf:"varint,1,opt,name=mailId,proto3" json:"mailId,omitempty"` // 邮件id
}

func (x *ReqMailRead) Reset() {
	*x = ReqMailRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMailRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailRead) ProtoMessage() {}

func (x *ReqMailRead) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailRead.ProtoReflect.Descriptor instead.
func (*ReqMailRead) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{6}
}

func (x *ReqMailRead) GetMailId() int32 {
	if x != nil {
		return x.MailId
	}
	return 0
}

type RspMailRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 0成功
	MailId int32 `protobuf:"varint,2,opt,name=mailId,proto3" json:"mailId,omitempty"` // 邮件id
}

func (x *RspMailRead) Reset() {
	*x = RspMailRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspMailRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailRead) ProtoMessage() {}

func (x *RspMailRead) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailRead.ProtoReflect.Descriptor instead.
func (*RspMailRead) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{7}
}

func (x *RspMailRead) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RspMailRead) GetMailId() int32 {
	if x != nil {
		return x.MailId
	}
	return 0
}

// 领取邮件 grp:14, cmd:2
type ReqMailReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailIds []int32 `protobuf:"varint,1,rep,packed,name=mailIds,proto3" json:"mailIds,omitempty"` // 邮件列表
}

func (x *ReqMailReward) Reset() {
	*x = ReqMailReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMailReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailReward) ProtoMessage() {}

func (x *ReqMailReward) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailReward.ProtoReflect.Descriptor instead.
func (*ReqMailReward) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{8}
}

func (x *ReqMailReward) GetMailIds() []int32 {
	if x != nil {
		return x.MailIds
	}
	return nil
}

type RspMailReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`          // 0成功
	Rewards *Rewards `protobuf:"bytes,2,opt,name=rewards,proto3" json:"rewards,omitempty"`         // 奖励
	MailIds []int32  `protobuf:"varint,3,rep,packed,name=mailIds,proto3" json:"mailIds,omitempty"` // 邮件列表
}

func (x *RspMailReward) Reset() {
	*x = RspMailReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspMailReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailReward) ProtoMessage() {}

func (x *RspMailReward) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailReward.ProtoReflect.Descriptor instead.
func (*RspMailReward) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{9}
}

func (x *RspMailReward) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RspMailReward) GetRewards() *Rewards {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *RspMailReward) GetMailIds() []int32 {
	if x != nil {
		return x.MailIds
	}
	return nil
}

// 删除邮件 grp:15, cmd:3
type ReqMailDel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailIds []int32 `protobuf:"varint,1,rep,packed,name=mailIds,proto3" json:"mailIds,omitempty"` // 邮件列表
}

func (x *ReqMailDel) Reset() {
	*x = ReqMailDel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqMailDel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMailDel) ProtoMessage() {}

func (x *ReqMailDel) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMailDel.ProtoReflect.Descriptor instead.
func (*ReqMailDel) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{10}
}

func (x *ReqMailDel) GetMailIds() []int32 {
	if x != nil {
		return x.MailIds
	}
	return nil
}

type RspMailDel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`          // 0成功
	MailIds []int32 `protobuf:"varint,2,rep,packed,name=mailIds,proto3" json:"mailIds,omitempty"` // 邮件列表
}

func (x *RspMailDel) Reset() {
	*x = RspMailDel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspMailDel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspMailDel) ProtoMessage() {}

func (x *RspMailDel) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspMailDel.ProtoReflect.Descriptor instead.
func (*RspMailDel) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{11}
}

func (x *RspMailDel) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RspMailDel) GetMailIds() []int32 {
	if x != nil {
		return x.MailIds
	}
	return nil
}

//==================== 支付 ====================//
// 预支付 grp:16, cmd:1
type ReqPrePay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RechargeId int32    `protobuf:"varint,1,opt,name=rechargeId,proto3" json:"rechargeId,omitempty"` // recharge表id
	App        *AppInfo `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`                // 前端上传的信息
}

func (x *ReqPrePay) Reset() {
	*x = ReqPrePay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqPrePay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPrePay) ProtoMessage() {}

func (x *ReqPrePay) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPrePay.ProtoReflect.Descriptor instead.
func (*ReqPrePay) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{12}
}

func (x *ReqPrePay) GetRechargeId() int32 {
	if x != nil {
		return x.RechargeId
	}
	return 0
}

func (x *ReqPrePay) GetApp() *AppInfo {
	if x != nil {
		return x.App
	}
	return nil
}

type RspPrePay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`  // 0成功1不满足支付条件 其他的错误码见upay文档 2 英雄背包已满 3 订阅信息更新请重新登陆
	OrderId string `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"` // 订单号
}

func (x *RspPrePay) Reset() {
	*x = RspPrePay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspPrePay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspPrePay) ProtoMessage() {}

func (x *RspPrePay) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspPrePay.ProtoReflect.Descriptor instead.
func (*RspPrePay) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{13}
}

func (x *RspPrePay) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RspPrePay) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// 支付领奖 grp:16, cmd:2
type ReqRewardPay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId      string        `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`           // prepay返回的订单号
	StoreId      string        `protobuf:"bytes,2,opt,name=storeId,proto3" json:"storeId,omitempty"`           // 商品id  <<"com.droidhang.test.diamond11">>
	App          *AppInfo      `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`                   // 前端上传的信息
	CurrencyInfo *CurrencyInfo `protobuf:"bytes,4,opt,name=currencyInfo,proto3" json:"currencyInfo,omitempty"` //货币信息
}

func (x *ReqRewardPay) Reset() {
	*x = ReqRewardPay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqRewardPay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRewardPay) ProtoMessage() {}

func (x *ReqRewardPay) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRewardPay.ProtoReflect.Descriptor instead.
func (*ReqRewardPay) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{14}
}

func (x *ReqRewardPay) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReqRewardPay) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ReqRewardPay) GetApp() *AppInfo {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *ReqRewardPay) GetCurrencyInfo() *CurrencyInfo {
	if x != nil {
		return x.CurrencyInfo
	}
	return nil
}

type RspRewardPay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`  // 0成功1验证失败
	Rewards *Rewards `protobuf:"bytes,2,opt,name=rewards,proto3" json:"rewards,omitempty"` // 奖励
	Cd      int32    `protobuf:"varint,3,opt,name=cd,proto3" json:"cd,omitempty"`          // 订阅到期cd
}

func (x *RspRewardPay) Reset() {
	*x = RspRewardPay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspRewardPay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspRewardPay) ProtoMessage() {}

func (x *RspRewardPay) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspRewardPay.ProtoReflect.Descriptor instead.
func (*RspRewardPay) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{15}
}

func (x *RspRewardPay) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RspRewardPay) GetRewards() *Rewards {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *RspRewardPay) GetCd() int32 {
	if x != nil {
		return x.Cd
	}
	return 0
}

//补单 grp:16, cmd:3
type ReqLoginRewardPay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId      string        `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`           // prepay返回的订单号
	StoreId      string        `protobuf:"bytes,2,opt,name=storeId,proto3" json:"storeId,omitempty"`           // 商品id  <<"com.droidhang.test.diamond11">>
	App          *AppInfo      `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`                   // 前端上传的信息
	CurrencyInfo *CurrencyInfo `protobuf:"bytes,4,opt,name=currencyInfo,proto3" json:"currencyInfo,omitempty"` //货币信息
}

func (x *ReqLoginRewardPay) Reset() {
	*x = ReqLoginRewardPay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLoginRewardPay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLoginRewardPay) ProtoMessage() {}

func (x *ReqLoginRewardPay) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLoginRewardPay.ProtoReflect.Descriptor instead.
func (*ReqLoginRewardPay) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{16}
}

func (x *ReqLoginRewardPay) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReqLoginRewardPay) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ReqLoginRewardPay) GetApp() *AppInfo {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *ReqLoginRewardPay) GetCurrencyInfo() *CurrencyInfo {
	if x != nil {
		return x.CurrencyInfo
	}
	return nil
}

type RspLoginRewardPay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`  // 0成功
	StoreId string `protobuf:"bytes,2,opt,name=storeId,proto3" json:"storeId,omitempty"` // 商品id  <<"com.droidhang.test.diamond11">>
}

func (x *RspLoginRewardPay) Reset() {
	*x = RspLoginRewardPay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspLoginRewardPay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspLoginRewardPay) ProtoMessage() {}

func (x *RspLoginRewardPay) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspLoginRewardPay.ProtoReflect.Descriptor instead.
func (*RspLoginRewardPay) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{17}
}

func (x *RspLoginRewardPay) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RspLoginRewardPay) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

//==================== 游戏设置 ====================//
//换头像 grp:17,cmd:1
type ReqChangeAvatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarId int32 `protobuf:"varint,1,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
}

func (x *ReqChangeAvatar) Reset() {
	*x = ReqChangeAvatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqChangeAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChangeAvatar) ProtoMessage() {}

func (x *ReqChangeAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChangeAvatar.ProtoReflect.Descriptor instead.
func (*ReqChangeAvatar) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{18}
}

func (x *ReqChangeAvatar) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

type RspChangeAvatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 0成功
	AvatarId int32 `protobuf:"varint,2,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
}

func (x *RspChangeAvatar) Reset() {
	*x = RspChangeAvatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspChangeAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspChangeAvatar) ProtoMessage() {}

func (x *RspChangeAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspChangeAvatar.ProtoReflect.Descriptor instead.
func (*RspChangeAvatar) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{19}
}

func (x *RspChangeAvatar) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RspChangeAvatar) GetAvatarId() int32 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

//换名字 grp:17,cmd:2
type ReqChangeName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ReqChangeName) Reset() {
	*x = ReqChangeName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqChangeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqChangeName) ProtoMessage() {}

func (x *ReqChangeName) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqChangeName.ProtoReflect.Descriptor instead.
func (*ReqChangeName) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{20}
}

func (x *ReqChangeName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RspChangeName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 0成功
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RspChangeName) Reset() {
	*x = RspChangeName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspChangeName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspChangeName) ProtoMessage() {}

func (x *RspChangeName) ProtoReflect() protoreflect.Message {
	mi := &file_logic_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspChangeName.ProtoReflect.Descriptor instead.
func (*RspChangeName) Descriptor() ([]byte, []int) {
	return file_logic_proto_rawDescGZIP(), []int{21}
}

func (x *RspChangeName) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RspChangeName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_logic_proto protoreflect.FileDescriptor

var file_logic_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x52,
	0x45, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x53, 0x79, 0x6e, 0x63, 0x22, 0xb6,
	0x01, 0x0a, 0x07, 0x52, 0x73, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x76, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x76, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x07,
	0x72, 0x6f, 0x6c, 0x65, 0x4d, 0x67, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x52, 0x45, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x4d, 0x67, 0x72,
	0x52, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x4d, 0x67, 0x72, 0x12, 0x1f, 0x0a, 0x03, 0x62, 0x61, 0x67,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x45, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x61, 0x67, 0x52, 0x03, 0x62, 0x61, 0x67, 0x12, 0x2b, 0x0a, 0x07, 0x4d, 0x61,
	0x69, 0x6c, 0x4d, 0x67, 0x72, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x45,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x4d, 0x67, 0x72, 0x52, 0x07,
	0x4d, 0x61, 0x69, 0x6c, 0x4d, 0x67, 0x72, 0x22, 0x41, 0x0a, 0x05, 0x52, 0x65, 0x71, 0x47, 0x6d,
	0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x52, 0x45, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x4d, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x8c, 0x01, 0x0a, 0x05, 0x52,
	0x73, 0x70, 0x47, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x07,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x52, 0x45, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73,
	0x52, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x52, 0x45, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x4d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x45, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x45, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x36, 0x0a, 0x0a, 0x52, 0x65, 0x71,
	0x55, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75,
	0x6d, 0x22, 0x7b, 0x0a, 0x0a, 0x52, 0x73, 0x70, 0x55, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x45, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x52, 0x07, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x25,
	0x0a, 0x0b, 0x52, 0x65, 0x71, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x61, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d,
	0x61, 0x69, 0x6c, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x0b, 0x52, 0x73, 0x70, 0x4d, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x61,
	0x69, 0x6c, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x22,
	0x6e, 0x0a, 0x0d, 0x52, 0x73, 0x70, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x45, 0x2e, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x52, 0x07, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x22,
	0x26, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07,
	0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x3e, 0x0a, 0x0a, 0x52, 0x73, 0x70, 0x4d, 0x61,
	0x69, 0x6c, 0x44, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07,
	0x6d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x73, 0x22, 0x50, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x50, 0x72,
	0x65, 0x50, 0x61, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x52, 0x45, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x70, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x61, 0x70, 0x70, 0x22, 0x3d, 0x0a, 0x09, 0x52, 0x73, 0x70,
	0x50, 0x72, 0x65, 0x50, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x71,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x50, 0x61, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x03, 0x61, 0x70, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x45, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x61,
	0x70, 0x70, 0x12, 0x3a, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x52, 0x45, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x63,
	0x0a, 0x0c, 0x52, 0x73, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x50, 0x61, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x45, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x73, 0x52, 0x07, 0x72, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x63, 0x64, 0x22, 0xa8, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x50, 0x61, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x03, 0x61, 0x70, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x52, 0x45, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x61,
	0x70, 0x70, 0x12, 0x3a, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x52, 0x45, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x45,
	0x0a, 0x11, 0x52, 0x73, 0x70, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x50, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x0f, 0x52, 0x73, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x0d, 0x52,
	0x65, 0x71, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x3b, 0x0a, 0x0d, 0x52, 0x73, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x2f, 0x70, 0x62, 0x67, 0x6f, 0x2f, 0x70, 0x62, 0x72, 0x65, 0x71, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logic_proto_rawDescOnce sync.Once
	file_logic_proto_rawDescData = file_logic_proto_rawDesc
)

func file_logic_proto_rawDescGZIP() []byte {
	file_logic_proto_rawDescOnce.Do(func() {
		file_logic_proto_rawDescData = protoimpl.X.CompressGZIP(file_logic_proto_rawDescData)
	})
	return file_logic_proto_rawDescData
}

var file_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_logic_proto_goTypes = []interface{}{
	(*ReqSync)(nil),           // 0: RE.Proto.ReqSync
	(*RspSync)(nil),           // 1: RE.Proto.RspSync
	(*ReqGm)(nil),             // 2: RE.Proto.ReqGm
	(*RspGm)(nil),             // 3: RE.Proto.RspGm
	(*ReqUseItem)(nil),        // 4: RE.Proto.ReqUseItem
	(*RspUseItem)(nil),        // 5: RE.Proto.RspUseItem
	(*ReqMailRead)(nil),       // 6: RE.Proto.ReqMailRead
	(*RspMailRead)(nil),       // 7: RE.Proto.RspMailRead
	(*ReqMailReward)(nil),     // 8: RE.Proto.ReqMailReward
	(*RspMailReward)(nil),     // 9: RE.Proto.RspMailReward
	(*ReqMailDel)(nil),        // 10: RE.Proto.ReqMailDel
	(*RspMailDel)(nil),        // 11: RE.Proto.RspMailDel
	(*ReqPrePay)(nil),         // 12: RE.Proto.ReqPrePay
	(*RspPrePay)(nil),         // 13: RE.Proto.RspPrePay
	(*ReqRewardPay)(nil),      // 14: RE.Proto.ReqRewardPay
	(*RspRewardPay)(nil),      // 15: RE.Proto.RspRewardPay
	(*ReqLoginRewardPay)(nil), // 16: RE.Proto.ReqLoginRewardPay
	(*RspLoginRewardPay)(nil), // 17: RE.Proto.RspLoginRewardPay
	(*ReqChangeAvatar)(nil),   // 18: RE.Proto.ReqChangeAvatar
	(*RspChangeAvatar)(nil),   // 19: RE.Proto.RspChangeAvatar
	(*ReqChangeName)(nil),     // 20: RE.Proto.ReqChangeName
	(*RspChangeName)(nil),     // 21: RE.Proto.RspChangeName
	(*RoleMgr)(nil),           // 22: RE.Proto.RoleMgr
	(*Bag)(nil),               // 23: RE.Proto.Bag
	(*MailMgr)(nil),           // 24: RE.Proto.MailMgr
	(GMType)(0),               // 25: RE.Proto.GMType
	(*Rewards)(nil),           // 26: RE.Proto.Rewards
	(*AppInfo)(nil),           // 27: RE.Proto.appInfo
	(*CurrencyInfo)(nil),      // 28: RE.Proto.currencyInfo
}
var file_logic_proto_depIdxs = []int32{
	22, // 0: RE.Proto.RspSync.roleMgr:type_name -> RE.Proto.RoleMgr
	23, // 1: RE.Proto.RspSync.bag:type_name -> RE.Proto.Bag
	24, // 2: RE.Proto.RspSync.MailMgr:type_name -> RE.Proto.MailMgr
	25, // 3: RE.Proto.ReqGm.type:type_name -> RE.Proto.GMType
	26, // 4: RE.Proto.RspGm.rewards:type_name -> RE.Proto.Rewards
	25, // 5: RE.Proto.RspGm.type:type_name -> RE.Proto.GMType
	26, // 6: RE.Proto.RspUseItem.rewards:type_name -> RE.Proto.Rewards
	26, // 7: RE.Proto.RspMailReward.rewards:type_name -> RE.Proto.Rewards
	27, // 8: RE.Proto.ReqPrePay.app:type_name -> RE.Proto.appInfo
	27, // 9: RE.Proto.ReqRewardPay.app:type_name -> RE.Proto.appInfo
	28, // 10: RE.Proto.ReqRewardPay.currencyInfo:type_name -> RE.Proto.currencyInfo
	26, // 11: RE.Proto.RspRewardPay.rewards:type_name -> RE.Proto.Rewards
	27, // 12: RE.Proto.ReqLoginRewardPay.app:type_name -> RE.Proto.appInfo
	28, // 13: RE.Proto.ReqLoginRewardPay.currencyInfo:type_name -> RE.Proto.currencyInfo
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_logic_proto_init() }
func file_logic_proto_init() {
	if File_logic_proto != nil {
		return
	}
	file_comm_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_logic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspGm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUseItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspUseItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMailRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspMailRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMailReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspMailReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqMailDel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspMailDel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqPrePay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspPrePay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqRewardPay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspRewardPay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLoginRewardPay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspLoginRewardPay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqChangeAvatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspChangeAvatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqChangeName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspChangeName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logic_proto_goTypes,
		DependencyIndexes: file_logic_proto_depIdxs,
		MessageInfos:      file_logic_proto_msgTypes,
	}.Build()
	File_logic_proto = out.File
	file_logic_proto_rawDesc = nil
	file_logic_proto_goTypes = nil
	file_logic_proto_depIdxs = nil
}

//IGameCtx ===================GameCtx消息传递结构
type IGameCtx interface {
	ApiModBefore()
}

type GameCtx struct {
	ctx        context.Context
	apiFunc    map[string]interface{}
	playerInfo *PlayerInfo
	wg         *sync.WaitGroup
}

type TaskFn = func()

type PlayerInfo struct {
	RoleId    int64
	SessionId int64
	Sid       int32
	TaskFn    chan TaskFn //异步消息
	Client    *pbgo.LogicClientInfo
}

func NewGameCtx(childCtx context.Context) *GameCtx {
	return &GameCtx{
		ctx:        childCtx,
		apiFunc:    make(map[string]interface{}),
		playerInfo: &PlayerInfo{},
		wg:         &sync.WaitGroup{},
	}
}

func (this_ *GameCtx) GoRun(fn func(ctx context.Context)) {
	this_.wg.Add(1)
	go func() {
		defer func() {
			this_.wg.Done()
		}()
		fn(this_.ctx)
	}()
}

func (this_ *GameCtx) WaitWg() {
	this_.wg.Wait()
}

//InitModAfter 初始化之后执行（此时所有的模块已经全部初始化完成）
func (this_ *GameCtx) InitModAfter() {
}

//ApiModBefore 调用apiMod前执行
func (this_ *GameCtx) ApiModBefore() {
}

//SyncBefore sync前执行
func (this_ *GameCtx) SyncBefore() {
}

//TaskFnCh 接收任务
func (this_ *GameCtx) TaskFnCh() <-chan TaskFn {
	return this_.playerInfo.TaskFn
}

//SendTask 发送任务
func (this_ *GameCtx) SendTask(taskFn TaskFn) {
	this_.playerInfo.TaskFn <- taskFn
}

func (this_ *GameCtx) RegApiFunc(apiFunc map[string]interface{}) {
	this_.apiFunc = apiFunc
}

func (this_ *GameCtx) GetApiFunc(modName string) (interface{}, bool) {
	ins, had := this_.apiFunc[modName]
	if had {
		ins.(IGameCtx).ApiModBefore()
		return ins, true
	}
	return nil, false
}

func (this_ *GameCtx) GetCtx() context.Context {
	return this_.ctx
}

func (this_ *GameCtx) SetPlayerInfo(info *PlayerInfo) {
	this_.playerInfo = info
}

func (this_ *GameCtx) SetSessionId(sessionId int64) {
	this_.playerInfo.SessionId = sessionId
}

func (this_ *GameCtx) GetSessionId() int64 {
	return this_.playerInfo.SessionId
}

func (this_ *GameCtx) Client() *pbgo.LogicClientInfo {
	return this_.playerInfo.Client
}

func (this_ *GameCtx) GetSid() int32 {
	return this_.playerInfo.Sid
}

func (this_ *GameCtx) GetRoleId() int64 {
	return this_.playerInfo.RoleId
}

func (this_ *GameCtx) Log() string {
	return "roleId:" + strconv.Itoa(int(this_.playerInfo.RoleId)) + ",sid:" + strconv.Itoa(int(this_.playerInfo.Sid))
}

//ReqMsg ===================ReqMsg消息传递结构
type ReqMsg struct {
	Msg      *Msg
	ProtoMsg proto.Message
}

type Msg struct {
	Grp  int32  // 消息组id
	Cmd  int32  // 消息的ID
	Data []byte // 消息的内容
}

func NewReqMsg(grp, cmd int32, bin []byte) *ReqMsg {
	return &ReqMsg{
		Msg: &Msg{
			Grp:  grp,
			Cmd:  cmd,
			Data: bin,
		},
		ProtoMsg: nil,
	}
}
func (this_ *ReqMsg) GetData() []byte {
	return this_.Msg.Data
}

func (this_ *ReqMsg) GetGrpId() int32 {
	return this_.Msg.Grp
}

func (this_ *ReqMsg) GetCmdId() int32 {
	return this_.Msg.Cmd
}

//GetPbReq 获取请求对应消息结构
func GetPbReq(grp, cmd int32) proto.Message {
	protoId := int(1000*grp + cmd)
	switch protoId {
	case 10001:
		return &ReqSync{}
	case 11001:
		return &ReqGm{}
	case 12001:
		return &ReqUseItem{}
	case 13001:
		return &ReqMailRead{}
	case 14002:
		return &ReqMailReward{}
	case 15003:
		return &ReqMailDel{}
	case 16001:
		return &ReqPrePay{}
	case 16002:
		return &ReqRewardPay{}
	case 16003:
		return &ReqLoginRewardPay{}
	case 17001:
		return &ReqChangeAvatar{}
	case 17002:
		return &ReqChangeName{}
	}
	return nil
}

//=====================grpId和cmdId常量定义
const (
	//GrpId10 =====================功能模块
	GrpId10      = 10
	CmdReqSyncId = 1
	//GrpId11 =====================功能模块
	GrpId11    = 11
	CmdReqGmId = 1
	//GrpId12 =====================功能模块
	GrpId12         = 12
	CmdReqUseItemId = 1
	//GrpId13 =====================功能模块
	GrpId13          = 13
	CmdReqMailReadId = 1
	//GrpId14 =====================功能模块
	GrpId14            = 14
	CmdReqMailRewardId = 2
	//GrpId15 =====================功能模块
	GrpId15         = 15
	CmdReqMailDelId = 3
	//GrpId16 =====================功能模块
	GrpId16                = 16
	CmdReqPrePayId         = 1
	CmdReqRewardPayId      = 2
	CmdReqLoginRewardPayId = 3
	//GrpId17 =====================功能模块
	GrpId17              = 17
	CmdReqChangeAvatarId = 1
	CmdReqChangeNameId   = 2
)

//==============GrpId10对应的请求结构体TModApi10

//TModApi10 注册了常量GrpId10的模块结构体需要继承TModApi10结构体，并重写接口方法
type TModApi10 struct {
	api IModApi10
	*GameCtx
}

//GrpId 该请求结构体对应的grpid
func (this_ *TModApi10) GrpId() int32 {
	return GrpId10
}

//InitMod 初始化
func (this_ *TModApi10) InitMod(gameCtx *GameCtx) {
	this_.GameCtx = gameCtx
}

//Dispatch 请求的消息分发，子类无需重写
func (this_ *TModApi10) Dispatch(req *ReqMsg) proto.Message {
	switch req.GetCmdId() {
	}
	return nil
}

//InitModApi 实现接口
func (this_ *TModApi10) InitModApi(iModReq IModApi10) {
	this_.api = iModReq
}

//ReqBefore 请求接口执行前操作,可被对应模块重写
func (this_ *TModApi10) ReqBefore() {
}

type IModApi10 interface {
}

//==============GrpId11对应的请求结构体TModApi11

//TModApi11 注册了常量GrpId11的模块结构体需要继承TModApi11结构体，并重写接口方法
type TModApi11 struct {
	api IModApi11
	*GameCtx
}

//GrpId 该请求结构体对应的grpid
func (this_ *TModApi11) GrpId() int32 {
	return GrpId11
}

//InitMod 初始化
func (this_ *TModApi11) InitMod(gameCtx *GameCtx) {
	this_.GameCtx = gameCtx
}

//Dispatch 请求的消息分发，子类无需重写
func (this_ *TModApi11) Dispatch(req *ReqMsg) proto.Message {
	switch req.GetCmdId() {
	case 1:
		return this_.api.ReqGm(req.ProtoMsg.(*ReqGm))
	}
	return nil
}

//InitModApi 实现接口
func (this_ *TModApi11) InitModApi(iModReq IModApi11) {
	this_.api = iModReq
}

//ReqBefore 请求接口执行前操作,可被对应模块重写
func (this_ *TModApi11) ReqBefore() {
}

type IModApi11 interface {
	ReqGm(req *ReqGm) *RspGm
}

//==============GrpId12对应的请求结构体TModApi12

//TModApi12 注册了常量GrpId12的模块结构体需要继承TModApi12结构体，并重写接口方法
type TModApi12 struct {
	api IModApi12
	*GameCtx
}

//GrpId 该请求结构体对应的grpid
func (this_ *TModApi12) GrpId() int32 {
	return GrpId12
}

//InitMod 初始化
func (this_ *TModApi12) InitMod(gameCtx *GameCtx) {
	this_.GameCtx = gameCtx
}

//Dispatch 请求的消息分发，子类无需重写
func (this_ *TModApi12) Dispatch(req *ReqMsg) proto.Message {
	switch req.GetCmdId() {
	case 1:
		return this_.api.ReqUseItem(req.ProtoMsg.(*ReqUseItem))
	}
	return nil
}

//InitModApi 实现接口
func (this_ *TModApi12) InitModApi(iModReq IModApi12) {
	this_.api = iModReq
}

//ReqBefore 请求接口执行前操作,可被对应模块重写
func (this_ *TModApi12) ReqBefore() {
}

type IModApi12 interface {
	ReqUseItem(req *ReqUseItem) *RspUseItem
}

//==============GrpId13对应的请求结构体TModApi13

//TModApi13 注册了常量GrpId13的模块结构体需要继承TModApi13结构体，并重写接口方法
type TModApi13 struct {
	api IModApi13
	*GameCtx
}

//GrpId 该请求结构体对应的grpid
func (this_ *TModApi13) GrpId() int32 {
	return GrpId13
}

//InitMod 初始化
func (this_ *TModApi13) InitMod(gameCtx *GameCtx) {
	this_.GameCtx = gameCtx
}

//Dispatch 请求的消息分发，子类无需重写
func (this_ *TModApi13) Dispatch(req *ReqMsg) proto.Message {
	switch req.GetCmdId() {
	case 1:
		return this_.api.ReqMailRead(req.ProtoMsg.(*ReqMailRead))
	}
	return nil
}

//InitModApi 实现接口
func (this_ *TModApi13) InitModApi(iModReq IModApi13) {
	this_.api = iModReq
}

//ReqBefore 请求接口执行前操作,可被对应模块重写
func (this_ *TModApi13) ReqBefore() {
}

type IModApi13 interface {
	ReqMailRead(req *ReqMailRead) *RspMailRead
}

//==============GrpId14对应的请求结构体TModApi14

//TModApi14 注册了常量GrpId14的模块结构体需要继承TModApi14结构体，并重写接口方法
type TModApi14 struct {
	api IModApi14
	*GameCtx
}

//GrpId 该请求结构体对应的grpid
func (this_ *TModApi14) GrpId() int32 {
	return GrpId14
}

//InitMod 初始化
func (this_ *TModApi14) InitMod(gameCtx *GameCtx) {
	this_.GameCtx = gameCtx
}

//Dispatch 请求的消息分发，子类无需重写
func (this_ *TModApi14) Dispatch(req *ReqMsg) proto.Message {
	switch req.GetCmdId() {
	case 2:
		return this_.api.ReqMailReward(req.ProtoMsg.(*ReqMailReward))
	}
	return nil
}

//InitModApi 实现接口
func (this_ *TModApi14) InitModApi(iModReq IModApi14) {
	this_.api = iModReq
}

//ReqBefore 请求接口执行前操作,可被对应模块重写
func (this_ *TModApi14) ReqBefore() {
}

type IModApi14 interface {
	ReqMailReward(req *ReqMailReward) *RspMailReward
}

//==============GrpId15对应的请求结构体TModApi15

//TModApi15 注册了常量GrpId15的模块结构体需要继承TModApi15结构体，并重写接口方法
type TModApi15 struct {
	api IModApi15
	*GameCtx
}

//GrpId 该请求结构体对应的grpid
func (this_ *TModApi15) GrpId() int32 {
	return GrpId15
}

//InitMod 初始化
func (this_ *TModApi15) InitMod(gameCtx *GameCtx) {
	this_.GameCtx = gameCtx
}

//Dispatch 请求的消息分发，子类无需重写
func (this_ *TModApi15) Dispatch(req *ReqMsg) proto.Message {
	switch req.GetCmdId() {
	case 3:
		return this_.api.ReqMailDel(req.ProtoMsg.(*ReqMailDel))
	}
	return nil
}

//InitModApi 实现接口
func (this_ *TModApi15) InitModApi(iModReq IModApi15) {
	this_.api = iModReq
}

//ReqBefore 请求接口执行前操作,可被对应模块重写
func (this_ *TModApi15) ReqBefore() {
}

type IModApi15 interface {
	ReqMailDel(req *ReqMailDel) *RspMailDel
}

//==============GrpId16对应的请求结构体TModApi16

//TModApi16 注册了常量GrpId16的模块结构体需要继承TModApi16结构体，并重写接口方法
type TModApi16 struct {
	api IModApi16
	*GameCtx
}

//GrpId 该请求结构体对应的grpid
func (this_ *TModApi16) GrpId() int32 {
	return GrpId16
}

//InitMod 初始化
func (this_ *TModApi16) InitMod(gameCtx *GameCtx) {
	this_.GameCtx = gameCtx
}

//Dispatch 请求的消息分发，子类无需重写
func (this_ *TModApi16) Dispatch(req *ReqMsg) proto.Message {
	switch req.GetCmdId() {
	case 1:
		return this_.api.ReqPrePay(req.ProtoMsg.(*ReqPrePay))
	case 2:
		return this_.api.ReqRewardPay(req.ProtoMsg.(*ReqRewardPay))
	case 3:
		return this_.api.ReqLoginRewardPay(req.ProtoMsg.(*ReqLoginRewardPay))
	}
	return nil
}

//InitModApi 实现接口
func (this_ *TModApi16) InitModApi(iModReq IModApi16) {
	this_.api = iModReq
}

//ReqBefore 请求接口执行前操作,可被对应模块重写
func (this_ *TModApi16) ReqBefore() {
}

type IModApi16 interface {
	ReqPrePay(req *ReqPrePay) *RspPrePay
	ReqRewardPay(req *ReqRewardPay) *RspRewardPay
	ReqLoginRewardPay(req *ReqLoginRewardPay) *RspLoginRewardPay
}

//==============GrpId17对应的请求结构体TModApi17

//TModApi17 注册了常量GrpId17的模块结构体需要继承TModApi17结构体，并重写接口方法
type TModApi17 struct {
	api IModApi17
	*GameCtx
}

//GrpId 该请求结构体对应的grpid
func (this_ *TModApi17) GrpId() int32 {
	return GrpId17
}

//InitMod 初始化
func (this_ *TModApi17) InitMod(gameCtx *GameCtx) {
	this_.GameCtx = gameCtx
}

//Dispatch 请求的消息分发，子类无需重写
func (this_ *TModApi17) Dispatch(req *ReqMsg) proto.Message {
	switch req.GetCmdId() {
	case 1:
		return this_.api.ReqChangeAvatar(req.ProtoMsg.(*ReqChangeAvatar))
	case 2:
		return this_.api.ReqChangeName(req.ProtoMsg.(*ReqChangeName))
	}
	return nil
}

//InitModApi 实现接口
func (this_ *TModApi17) InitModApi(iModReq IModApi17) {
	this_.api = iModReq
}

//ReqBefore 请求接口执行前操作,可被对应模块重写
func (this_ *TModApi17) ReqBefore() {
}

type IModApi17 interface {
	ReqChangeAvatar(req *ReqChangeAvatar) *RspChangeAvatar
	ReqChangeName(req *ReqChangeName) *RspChangeName
}
