package config

type GlobalLanguageCfg struct {
	Id   string
	Name string
}

type GlobalLanguageTable struct {
	data map[string]*GlobalLanguageCfg
}

var GlobalLanguageData = &GlobalLanguageTable{
	data: map[string]*GlobalLanguageCfg{},
}

func (table *GlobalLanguageTable) Get(id string) *GlobalLanguageCfg {
	return table.data[id]
}

func (table *GlobalLanguageTable) GetAll() []string {
	return globalLanguageKeys
}

var globalLanguageValues = []*GlobalLanguageCfg{
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
	{},
}

var globalLanguageKeys = []string{
	ConfNoMana, ConfShop, ConfHero, ConfArtifact, ConfTerritory, ConfMercenary, ConfLogin1, ConfLogin2, ConfLogin3, ConfLogin4,
	ConfTips, ConfOk, ConfCancel, ConfRoleinfo1, ConfRoleinfo2, ConfRoleinfo3, ConfRoleinfo4, ConfRoleinfo5, ConfRoleinfo6, ConfRoleinfo7,
	ConfRoleinfo9, ConfRoleinfo10, ConfRoleinfo11, ConfRoleSkill1, ConfRoleSkill2, ConfRoleSkill3, ConfRoleSkill4, ConfRloeEquip1, ConfRloeEquip2, ConfRloeEquip3,
	ConfRloeEquip4, ConfRloeEquip5, ConfRloeEquip6, ConfRloeEquip7, ConfRloeEquip8, ConfRloeEquip11, ConfEquip1, ConfEquip2, ConfCommon1, ConfNewHero,
	ConfHeroTitle1, ConfHeroTitle2, ConfHeroBtn1, ConfHeroBtn2, ConfHeroTips1, ConfHeroTitle3, ConfHeroTips2, ConfHeroTitle4, ConfHeroTips3, ConfCommon2,
	ConfSkillTips1, ConfEquipTips1, ConfEquipTips2, ConfEquipTips3, ConfAscendTips1, ConfStageTIps1, ConfCommon3, ConfServerCode1, ConfServerCode2, ConfServerCode3,
	ConfCommon4, ConfServerCode4, ConfServerCode5, ConfServerCode6, ConfServerCode7, ConfServerCode8, ConfServerCode9, ConfServerCode10, ConfServerCode11, ConfServerCode12,
	ConfServerCode13, ConfServerCode14, ConfServerCode15, ConfServerCode16, ConfServerCode17, ConfServerCode18, ConfServerCode19, ConfServerCode20, ConfServerCode21, ConfServerCode22,
	ConfServerCode23, ConfServerCode24, ConfServerCode25, ConfShortcuts1, ConfShortcuts2, ConfCommon5, ConfServerCode26, ConfServerCode27, ConfServerCode28, ConfServerCode29,
	ConfShortcuts3, ConfCommon6, ConfSkillTitle1, ConfTalentTitle1, ConfTalentTitle2, ConfTalentTitle3, ConfTalentTips1, ConfTalentTips2, ConfTalentTips3, ConfTalentTips4,
	ConfTalentReset, ConfTalentResetTips1, ConfTalentResetTips2, ConfSkillTips2, ConfSkillTips3, ConfSkillTips4, ConfMagic, ConfMagicTips, ConfSkillTips5, ConfSkillTips6,
	ConfServerCode30, ConfBagTitle, ConfBagTab1, ConfBagTab2, ConfBagTab3, ConfBagTab4, ConfBagTips1, ConfBagBtn1, ConfBagBtn2, ConfBagBtn3,
	ConfBagTips2, ConfBagTips3, ConfBagTips4, ConfBagTips5, ConfServerCode31, ConfTalentResetTips3, ConfEquipTips4, ConfSkillTips7, ConfSkillTips8, ConfSkillTips9,
	ConfSkillTips10, ConfTerritoryTips1, ConfTerritoryTips2, ConfTerritoryTips3, ConfTerritory2, ConfTerritory3, ConfTerritoryBtn, ConfTerritorySucceed, ConfTerritoryFailed, ConfTerritoryFailed2,
	ConfTerritory4, ConfTerritory5, ConfTerritory6, ConfTerritory7, ConfTerritory8, ConfServerCode32, ConfServerCode33, ConfServerCode34, ConfServerCode35, ConfServerCode36,
	ConfServerCode37, ConfServerCode38, ConfCraftsman1, ConfCraftsman2, ConfCraftsman3, ConfCraftsman4, ConfCraftsman5, ConfBuildBtn, ConfAttributes1, ConfAttributes2,
	ConfAttributes3, ConfAttributes4, ConfCraftsman6, ConfCommon7, ConfArtifactTitle1, ConfArtifactTag1, ConfArtifactTitle2, ConfArtifactTag2, ConfArtifactBtn1, ConfArtifactBtn2,
	ConfArtifactTips, ConfServerCode39, ConfServerCode40, ConfServerCode41, ConfServerCode42, ConfServerCode43, ConfServerCode44, ConfServerCode45, ConfServerCode46, ConfServerCode47,
	ConfServerCode48, ConfServerCode49, ConfServerCode50, ConfServerCode51, ConfServerCode52, ConfServerCode53, ConfServerCode54, ConfServerCode55, ConfMercenaryPro1, ConfMercenaryBtn1,
	ConfMercenaryBtn2, ConfMercenaryBtn3, ConfMercenarySta1, ConfMercenarySta3, ConfMercenaryTitle1, ConfMercenaryBtn4, ConfMercenaryTips, ConfMercenaryTitle3, ConfMercenaryTips2, ConfMercenaryDialog1,
	ConfMercenaryText1, ConfMercenaryText2, ConfSkillTips11, ConfMercenaryTips3, ConfMercenaryTips4, ConfMercenaryBtn5, ConfMercenaryTips5, ConfAddSkill, ConfSetting, ConfHangingRewards1,
	ConfHangingRewards2, ConfHangingRewards3, ConfHangingRewards5, ConfHangingRewards6, ConfInstanceTag1, ConfInstanceTag2, ConfInstanceTag3, ConfInstanceTag4, ConfInstanceMainTitle1, ConfInstanceMainTitle2,
	ConfInstanceMainTitle3, ConfInstanceMainTitle4, ConfInstanceTitle1, ConfInstanceBtn1, ConfInstanceBtn2, ConfInstanceTips1, ConfInstanceTitle2, ConfInstanceTips2, ConfInstanceRankTitle1, ConfInstanceRankTitle2,
	ConfInstanceRankTitle3, ConfInstanceRankTitle4, ConfInstanceRankTitle5, ConfInstanceRankTips1, ConfInstanceBtn3, ConfInstanceMainBtn1, ConfRankCommonText1, ConfInstanceTips3, ConfInstanceTips4, ConfInstanceText1,
	ConfInstanceText2, ConfInstanceTips6, ConfInstanceTips5, ConSettingTitle, ConSettingBtn1, ConSettingBtn2, ConSettingBtn3, ConSettingBtn4, ConSettingBtn5, ConSettingBtn6,
	ConSettingBtn7, ConSettingBtn8, ConSettingBtn9, ConSettingBtn10, ConSettingBtn11, ConSettingBtn12, ConSettingBtn13, ConSettingBtn14, ConSettingHeadTitle, ConSettingNameTips1,
	ConSettingNameBtn1, ConSettingNameBtn2, ConSettingTips1, ConSettingTips2, ConfInstanceTips7, ConfCommon8, ConfCommon9, ConfCommon10, ConfSummonTitle1, ConfSummonTitle2,
	ConfSummonBtn, ConfSummonText, ConfShopTag1, ConfShopTag2, ConfShopTag3, ConfShopTag4, ConfShopTag5, ConfShopTag6, ConfMonthCardTips1, ConfPurchaseLimit,
	ConfSummonExchangeTips, ConfSummonTips, ConfShopWarriorOrder1, ConfShopWarriorOrder2, ConfShopWarriorOrder3, ConfShopWarriorOrder4, ConfRecharge1, ConfRecharge2, ConfRecharge3, ConfRecharge4,
	ConfRecharge5, ConfShopFirstRecharge1, ConfShopFirstRecharge2, ConfShopFirstRecharge3, ConfShopFirstRecharge4, ConfShopFirstRecharge7, ConfShopFirstRecharge8, ConfShopFirstRecharge9, ConfNetworkTips1, ConfNetworkTips2,
	ConfNetworkTips3, ConfMailTips1, ConfMailTips2, ConfMailTips3, ConfMailTips4, ConfMailTips5, ConfMailTips6, ConfMailTips7, ConfMailTips8, ConfMailTips9,
	ConfMailTips10, ConfStoreText1, ConfStoreBtn1, ConfStoreBtn2, ConfStoreBtn3, ConfPackageText1, ConfPackageText2, ConfMonthCardText1, ConfMonthCardText2, ConfMonthCardText3,
	ConfMonthCardlabel1, ConfMonthCardlabel2, ConfMonthCardTitle1, ConfMonthCardTitle2, ConfMonthCardTitle3, ConfTopUpTip1, ConfTopUpTip2, ConfCopySuccess, ConfLanguageSettingText, ConfLanguageEnglish,
	ConfLanguageChinese, ConfMonthCardText4, ConfMonthCardText5, ConfPlayerName, ConfPlayerRename, ConfSettingTips3, ConfServerCode56, ConfRefreshTime, ConfEquipEnhanceTips, ConfSettingHeadText,
	ConfHeadLockedTips, ConfNewFunctionOpen, ConfCommon11, ConfMailSender, ConfAttributes5, ConfEquipTips5, ConfNewPlayer1, ConfNewPlayer2, ConfNewPlayer3, ConfNewPlayer4,
	ConfNewPlayer5, ConfNewPlayer6, ConfNewPlayer7, ConfNewPlayer8, ConfNewPlayer9, ConfNewPlayer10, ConfChat1, ConfChat2, ConfChat3, ConfChat4,
	ConfChat5, ConfChat6, ConfChat7, ConfChat8, ConfChat9, ConfChat10, ConfLogin5, ConfLogin6, ConfLogin7, ConfLogin8,
	ConfChat11, ConfChat12, ConfChat13, ConfChat14, ConfChat15, ConfChat16, ConfChat17, ConfChat18, ConfChat19, ConfChat20,
	ConfChat21, ConfChat22, ConfStart, ConfLogin9, ConfBattleDateErr, ConfActNoviceLogin, ConfChat23, ConfChat24, ConfChat25, ConfChat26,
	ConfEquip3, ConfEquipDecomposeText, ConfHelpTitle, ConfTaskTips1, DailyTaskTitle, Oneclicktoget, Completed, ConfDamageTotal, ConfArtifactAttriTitle,
}

func init() {
	GlobalLanguageData.data = make(map[string]*GlobalLanguageCfg)
	for i := 0; i < len(globalLanguageKeys); i++ {
		GlobalLanguageData.data[globalLanguageKeys[i]] = globalLanguageValues[i]
	}
}
