package config

type MonsterCfg struct {
	Id             int32
	MonsterType    int32
	Qlt            int32
	Group          int32
	Job            int32
	SkillGroup     []int32
	SkillLevel     []int32
	BattleModel    int32
	Model          string
	HeadIcon       string
	HpB            int64
	AdB            int64
	MpB            int64
	DrB            int64
	MdfB           int64
	HitB           int32
	DodgeB         int32
	AspdB          int32
	AdCritB        int32
	MpCritB        int32
	CritDmgAdd     int32
	AdCritResistB  int32
	MpCritResistB  int32
	LifeStealAdd   int32
	MpLifeStealAdd int32
}

type MonsterTable struct {
	data map[int32]*MonsterCfg
}

var MonsterData = &MonsterTable{
	data: map[int32]*MonsterCfg{},
}

func (table *MonsterTable) Get(id int32) *MonsterCfg {
	return table.data[id]
}

func (table *MonsterTable) GetAll() []int32 {
	return monsterKeys
}

var monsterValues = []*MonsterCfg{
	{
		Id:          10013,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			100139,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10015,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			100139,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10023,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			100239,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10025,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			100239,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10033,
		MonsterType: 3,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			100339,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10043,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			100439,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10045,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			100439,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10053,
		MonsterType: 3,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			100539,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10055,
		MonsterType: 3,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			100539,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10063,
		MonsterType: 3,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			100639,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10073,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			100739,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10075,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			100739,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10083,
		MonsterType: 3,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			100839,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10085,
		MonsterType: 3,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			100839,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10093,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			100939,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10095,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			100939,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10103,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			101039,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10105,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			101039,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10112,
		MonsterType: 1,
		Qlt:         1,
		Group:       4,
		SkillGroup: []int32{
			101129,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10131,
		MonsterType: 1,
		Qlt:         1,
		Group:       4,
		SkillGroup: []int32{
			101319,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10142,
		MonsterType: 1,
		Qlt:         1,
		Group:       4,
		SkillGroup: []int32{
			101429,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10145,
		MonsterType: 1,
		Qlt:         1,
		Group:       4,
		SkillGroup: []int32{
			101429,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10151,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			101519,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10161,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			101619,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10165,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			101619,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10172,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			101729,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10175,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			101729,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10181,
		MonsterType: 1,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			101819,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10185,
		MonsterType: 1,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			101819,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10191,
		MonsterType: 1,
		Qlt:         1,
		Group:       4,
		SkillGroup: []int32{
			101919,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10195,
		MonsterType: 1,
		Qlt:         1,
		Group:       4,
		SkillGroup: []int32{
			101919,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10202,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			102029,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10205,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			102029,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10211,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			102119,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10215,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			102119,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10221,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			102219,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10225,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			102219,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10232,
		MonsterType: 1,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			102329,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10235,
		MonsterType: 1,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			102329,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10241,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			102419,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10245,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			102419,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10251,
		MonsterType: 1,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			102519,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10262,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			102629,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10271,
		MonsterType: 1,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			102719,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10281,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			102819,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10292,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			102929,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10295,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			102929,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10301,
		MonsterType: 1,
		Qlt:         1,
		Group:       4,
		SkillGroup: []int32{
			103019,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10305,
		MonsterType: 1,
		Qlt:         1,
		Group:       4,
		SkillGroup: []int32{
			103019,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10311,
		MonsterType: 1,
		Qlt:         1,
		Group:       4,
		SkillGroup: []int32{
			103119,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10322,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			103229,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10325,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			103229,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10331,
		MonsterType: 1,
		Qlt:         1,
		Group:       4,
		SkillGroup: []int32{
			103319,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10341,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			103419,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10345,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			103419,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10352,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			103529,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10361,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			103619,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10371,
		MonsterType: 1,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			103719,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10375,
		MonsterType: 1,
		Qlt:         1,
		Group:       8,
		SkillGroup: []int32{
			103719,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10382,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			103829,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10385,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			103829,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10391,
		MonsterType: 1,
		Qlt:         1,
		Group:       4,
		SkillGroup: []int32{
			103919,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10395,
		MonsterType: 1,
		Qlt:         1,
		Group:       4,
		SkillGroup: []int32{
			103919,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          10401,
		MonsterType: 1,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			104019,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
	{
		Id:          1000001,
		MonsterType: 3,
		Qlt:         1,
		Group:       2,
		SkillGroup: []int32{
			1100100,
		},
		SkillLevel: []int32{
			1,
		},
		HpB:            1,
		AdB:            1,
		MpB:            1,
		DrB:            0,
		MdfB:           0,
		HitB:           0,
		DodgeB:         0,
		AspdB:          200,
		AdCritB:        0,
		MpCritB:        0,
		CritDmgAdd:     0,
		AdCritResistB:  0,
		MpCritResistB:  0,
		LifeStealAdd:   0,
		MpLifeStealAdd: 0,
	},
}

var monsterKeys = []int32{
	10013, 10015, 10023, 10025, 10033, 10043, 10045, 10053, 10055, 10063,
	10073, 10075, 10083, 10085, 10093, 10095, 10103, 10105, 10112, 10131,
	10142, 10145, 10151, 10161, 10165, 10172, 10175, 10181, 10185, 10191,
	10195, 10202, 10205, 10211, 10215, 10221, 10225, 10232, 10235, 10241,
	10245, 10251, 10262, 10271, 10281, 10292, 10295, 10301, 10305, 10311,
	10322, 10325, 10331, 10341, 10345, 10352, 10361, 10371, 10375, 10382,
	10385, 10391, 10395, 10401, 1000001,
}

func init() {
	MonsterData.data = make(map[int32]*MonsterCfg)
	for i := 0; i < len(monsterKeys); i++ {
		MonsterData.data[monsterKeys[i]] = monsterValues[i]
	}
}
