package config

type AttributesCfg struct {
	Id          int32
	Attrib      string
	AttribType  int32
	IsCalculate int32
	Icon        string
}

type AttributesTable struct {
	data                     map[int32]*AttributesCfg
	attributesAttribIndexMap map[string][]int32
}

var AttributesData = &AttributesTable{
	data: map[int32]*AttributesCfg{},
	attributesAttribIndexMap: map[string][]int32{
		"ad":                 {20},
		"adB":                {23},
		"adBP":               {22},
		"adBasic":            {25},
		"adCrit":             {80},
		"adCritB":            {83},
		"adCritBP":           {82},
		"adCritBasic":        {85},
		"adCritGrowth":       {81},
		"adCritResist":       {110},
		"adCritResistB":      {113},
		"adCritResistBP":     {112},
		"adCritResistBasic":  {115},
		"adCritResistGrowth": {111},
		"adCritResistTP":     {114},
		"adCritTP":           {84},
		"adDmgPer":           {193},
		"adDmgResist":        {173},
		"adGrowth":           {21},
		"adTP":               {24},
		"aspd":               {70},
		"aspdB":              {73},
		"aspdBP":             {72},
		"aspdBasic":          {75},
		"aspdGrowth":         {71},
		"aspdTP":             {74},
		"bossAdDmgPer":       {233},
		"bossAdDmgResist":    {253},
		"bossMpDmgPer":       {243},
		"bossMpDmgResist":    {263},
		"clickAdDmgPer":      {213},
		"clickMpDmgPer":      {223},
		"critDmg":            {100},
		"critDmgAdd":         {103},
		"critDmgBP":          {102},
		"critDmgBasic":       {105},
		"critDmgGrowth":      {101},
		"critDmgTP":          {104},
		"dodge":              {160},
		"dodgeB":             {163},
		"dodgeBP":            {162},
		"dodgeBasic":         {165},
		"dodgeGrowth":        {161},
		"dodgeTP":            {164},
		"dr":                 {40},
		"drB":                {43},
		"drBP":               {42},
		"drBasic":            {45},
		"drGrowth":           {41},
		"drTP":               {44},
		"hit":                {150},
		"hitB":               {153},
		"hitBP":              {152},
		"hitBasic":           {155},
		"hitGrowth":          {151},
		"hitTP":              {154},
		"hp":                 {10},
		"hpB":                {13},
		"hpBP":               {12},
		"hpBasic":            {15},
		"hpGrowth":           {11},
		"hpTP":               {14},
		"lifeSteal":          {130},
		"lifeStealAdd":       {133},
		"lifeStealBP":        {132, 142},
		"lifeStealBasic":     {135},
		"lifeStealGrowth":    {131, 141},
		"lifeStealTP":        {134, 144},
		"mana":               {60},
		"manaB":              {63},
		"manaBP":             {62},
		"manaBasic":          {65},
		"manaGrowth":         {61},
		"manaTP":             {64},
		"mdf":                {50},
		"mdfB":               {53},
		"mdfBP":              {52},
		"mdfBasic":           {55},
		"mdfGrowth":          {51},
		"mdfTP":              {54},
		"monsterAdDmgPer":    {273},
		"monsterAdDmgResist": {293},
		"monsterMpDmgPer":    {283},
		"monsterMpDmgResist": {303},
		"mp":                 {30},
		"mpB":                {33},
		"mpBP":               {32},
		"mpBasic":            {35},
		"mpCrit":             {90},
		"mpCritB":            {93},
		"mpCritBP":           {92},
		"mpCritBasic":        {95},
		"mpCritGrowth":       {91},
		"mpCritResist":       {120},
		"mpCritResistB":      {123},
		"mpCritResistBP":     {122},
		"mpCritResistBasic":  {125},
		"mpCritResistGrowth": {121},
		"mpCritResistTP":     {124},
		"mpCritTP":           {94},
		"mpDmgPer":           {203},
		"mpDmgResist":        {183},
		"mpGrowth":           {31},
		"mpLifeSteal":        {140},
		"mpLifeStealAdd":     {143},
		"mpLifeStealBasic":   {145},
		"mpTP":               {34},
		"skillAdDmgPer":      {313},
		"skillMpDmgPer":      {323},
	},
}

func (table *AttributesTable) Get(id int32) *AttributesCfg {
	return table.data[id]
}

func (table *AttributesTable) GetAll() []int32 {
	return attributesKeys
}

var attributesValues = []*AttributesCfg{
	{
		Id:          10,
		Attrib:      "hp",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          11,
		Attrib:      "hpGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          12,
		Attrib:      "hpBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          13,
		Attrib:      "hpB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          14,
		Attrib:      "hpTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          15,
		Attrib:      "hpBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          20,
		Attrib:      "ad",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          21,
		Attrib:      "adGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          22,
		Attrib:      "adBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          23,
		Attrib:      "adB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          24,
		Attrib:      "adTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          25,
		Attrib:      "adBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          30,
		Attrib:      "mp",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          31,
		Attrib:      "mpGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          32,
		Attrib:      "mpBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          33,
		Attrib:      "mpB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          34,
		Attrib:      "mpTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          35,
		Attrib:      "mpBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          40,
		Attrib:      "dr",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          41,
		Attrib:      "drGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          42,
		Attrib:      "drBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          43,
		Attrib:      "drB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          44,
		Attrib:      "drTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          45,
		Attrib:      "drBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          50,
		Attrib:      "mdf",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          51,
		Attrib:      "mdfGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          52,
		Attrib:      "mdfBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          53,
		Attrib:      "mdfB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          54,
		Attrib:      "mdfTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          55,
		Attrib:      "mdfBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          60,
		Attrib:      "mana",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          61,
		Attrib:      "manaGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          62,
		Attrib:      "manaBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          63,
		Attrib:      "manaB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          64,
		Attrib:      "manaTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          65,
		Attrib:      "manaBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          70,
		Attrib:      "aspd",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          71,
		Attrib:      "aspdGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          72,
		Attrib:      "aspdBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          73,
		Attrib:      "aspdB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          74,
		Attrib:      "aspdTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          75,
		Attrib:      "aspdBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          80,
		Attrib:      "adCrit",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          81,
		Attrib:      "adCritGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          82,
		Attrib:      "adCritBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          83,
		Attrib:      "adCritB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          84,
		Attrib:      "adCritTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          85,
		Attrib:      "adCritBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          90,
		Attrib:      "mpCrit",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          91,
		Attrib:      "mpCritGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          92,
		Attrib:      "mpCritBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          93,
		Attrib:      "mpCritB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          94,
		Attrib:      "mpCritTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          95,
		Attrib:      "mpCritBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          100,
		Attrib:      "critDmg",
		AttribType:  2,
		IsCalculate: 0,
	},
	{
		Id:          101,
		Attrib:      "critDmgGrowth",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          102,
		Attrib:      "critDmgBP",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          103,
		Attrib:      "critDmgAdd",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          104,
		Attrib:      "critDmgTP",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          105,
		Attrib:      "critDmgBasic",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          110,
		Attrib:      "adCritResist",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          111,
		Attrib:      "adCritResistGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          112,
		Attrib:      "adCritResistBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          113,
		Attrib:      "adCritResistB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          114,
		Attrib:      "adCritResistTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          115,
		Attrib:      "adCritResistBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          120,
		Attrib:      "mpCritResist",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          121,
		Attrib:      "mpCritResistGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          122,
		Attrib:      "mpCritResistBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          123,
		Attrib:      "mpCritResistB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          124,
		Attrib:      "mpCritResistTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          125,
		Attrib:      "mpCritResistBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          130,
		Attrib:      "lifeSteal",
		AttribType:  2,
		IsCalculate: 0,
	},
	{
		Id:          131,
		Attrib:      "lifeStealGrowth",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          132,
		Attrib:      "lifeStealBP",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          133,
		Attrib:      "lifeStealAdd",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          134,
		Attrib:      "lifeStealTP",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          135,
		Attrib:      "lifeStealBasic",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          140,
		Attrib:      "mpLifeSteal",
		AttribType:  2,
		IsCalculate: 0,
	},
	{
		Id:          141,
		Attrib:      "lifeStealGrowth",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          142,
		Attrib:      "lifeStealBP",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          143,
		Attrib:      "mpLifeStealAdd",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          144,
		Attrib:      "lifeStealTP",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          145,
		Attrib:      "mpLifeStealBasic",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          150,
		Attrib:      "hit",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          151,
		Attrib:      "hitGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          152,
		Attrib:      "hitBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          153,
		Attrib:      "hitB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          154,
		Attrib:      "hitTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          155,
		Attrib:      "hitBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          160,
		Attrib:      "dodge",
		AttribType:  1,
		IsCalculate: 0,
	},
	{
		Id:          161,
		Attrib:      "dodgeGrowth",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          162,
		Attrib:      "dodgeBP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          163,
		Attrib:      "dodgeB",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          164,
		Attrib:      "dodgeTP",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          165,
		Attrib:      "dodgeBasic",
		AttribType:  1,
		IsCalculate: 1,
	},
	{
		Id:          173,
		Attrib:      "adDmgResist",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          183,
		Attrib:      "mpDmgResist",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          193,
		Attrib:      "adDmgPer",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          203,
		Attrib:      "mpDmgPer",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          213,
		Attrib:      "clickAdDmgPer",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          223,
		Attrib:      "clickMpDmgPer",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          233,
		Attrib:      "bossAdDmgPer",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          243,
		Attrib:      "bossMpDmgPer",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          253,
		Attrib:      "bossAdDmgResist",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          263,
		Attrib:      "bossMpDmgResist",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          273,
		Attrib:      "monsterAdDmgPer",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          283,
		Attrib:      "monsterMpDmgPer",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          293,
		Attrib:      "monsterAdDmgResist",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          303,
		Attrib:      "monsterMpDmgResist",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          313,
		Attrib:      "skillAdDmgPer",
		AttribType:  2,
		IsCalculate: 1,
	},
	{
		Id:          323,
		Attrib:      "skillMpDmgPer",
		AttribType:  2,
		IsCalculate: 1,
	},
}

var attributesKeys = []int32{
	10, 11, 12, 13, 14, 15, 20, 21, 22, 23,
	24, 25, 30, 31, 32, 33, 34, 35, 40, 41,
	42, 43, 44, 45, 50, 51, 52, 53, 54, 55,
	60, 61, 62, 63, 64, 65, 70, 71, 72, 73,
	74, 75, 80, 81, 82, 83, 84, 85, 90, 91,
	92, 93, 94, 95, 100, 101, 102, 103, 104, 105,
	110, 111, 112, 113, 114, 115, 120, 121, 122, 123,
	124, 125, 130, 131, 132, 133, 134, 135, 140, 141,
	142, 143, 144, 145, 150, 151, 152, 153, 154, 155,
	160, 161, 162, 163, 164, 165, 173, 183, 193, 203,
	213, 223, 233, 243, 253, 263, 273, 283, 293, 303,
	313, 323,
}

func init() {
	AttributesData.data = make(map[int32]*AttributesCfg)
	for i := 0; i < len(attributesKeys); i++ {
		AttributesData.data[attributesKeys[i]] = attributesValues[i]
	}
}

func (table *AttributesTable) GetByAttrib(Attrib string) (res []*AttributesCfg) {
	for _, i := range table.attributesAttribIndexMap[Attrib] {
		res = append(res, table.Get(i))
	}
	return
}
